#!/usr/bin/with-contenv sh

if [ -z "${SPARK_MASTERURL}" ]; then
    export SPARK_OPTIONS="org.apache.spark.deploy.master.Master"
    printf "%s" "${SPARK_OPTIONS}" > /var/run/s6/container_environment/SPARK_OPTIONS
else
    export SPARK_OPTIONS="org.apache.spark.deploy.worker.Worker ${SPARK_MASTERURL}"
    printf "%s" "${SPARK_OPTIONS}" > /var/run/s6/container_environment/SPARK_OPTIONS
fi
