version: '2'

services:
    consul:
        image: bhuisgen/alpine-consul
        environment:
            - CONSUL_OPTIONS=-server -bootstrap-expect=1 -client 0.0.0.0 -ui    # minimal server options

    influxdb:
        depends_on:
            - consul
        image: bhuisgen/alpine-influxdb
        ports:
            - "8083:8083"
            - "8086:8086"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            #- /host/data:/var/lib/influxdb                     # volume for data
        environment:
            - CONSUL_AGENT=consul                               # consul agent hostname/IP
            #- CONSUL_PORT=8500                                 # consul agent port
            #- CONSUL_KEYPREFIX=path/prefix/                    # consul key prefix path
            - CONSUL_SERVICENAME=influxdb                       # consul service name
            - CONSUL_SERVICETAGS=dev                            # consul service tag
            - CONSUL_SERVICEPORT=8086                           # consul service port
            - CONSUL_CHECKTYPE=tcp                              # consul health check type
            #- INFLUXDB_CONFIGSCRIPT=/root/influxdb/config.sh   # custom configuration script
