version: '3.7'

volumes:
    influxdb:

services:
    influxdb:
        image: bhuisgen/alpine-influxdb
        ports:
            - "8083:8083"
            - "8086:8086"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - influxdb:/var/lib/influxdb            # volume for data
        environment:
            - ENV=local                             # environment name
            - INFLUXDB_TEMPLATE=generic             # configuration template

            #
            # template generic
            #
