version: '3.5'

volumes:
    influxdb:

services:
    influxdb:
        depends_on:
            - consul                                # consul agent
        image: bhuisgen/alpine-influxdb
        ports:
            - "8083:8083"
            - "8086:8086"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - influxdb:/var/lib/influxdb            # volume for data
        environment:
            - ENV=local                             # environment name
            - CONSUL_AGENT=consul                   # consul agent hostname/IP
            #- CONSUL_PORT=8500                     # consul agent port
            #- CONSUL_KEYPREFIX=path/prefix/        # consul key prefix path
            - CONSUL_SERVICENAME=influxdb           # consul service name
            - CONSUL_SERVICETAGS=local              # consul service tag
            - CONSUL_SERVICEPORT=8086               # consul service port
            - CONSUL_CHECKTYPE=tcp                  # consul health check type
