#!/usr/bin/with-contenv sh

if [ ! -z ${CONSUL_AGENT} ] && [ ${CONSULTEMPLATE_CONTAINER} -eq 1 ]; then
    echo "==> Removing container configuration"

    rm -f /etc/cont-consul/services.d/container.json /etc/cont-consul/checks.d/container-*.json
fi

if [ ! -z ${CONSUL_AGENT} ] && [ ${CONSULTEMPLATE_SERVICES} -eq 1 ]; then
    echo "==> Disabling services configuration"

    touch /etc/services.d/consul-template/down
fi
