#!/usr/bin/with-contenv sh

if [ ! -z "${XVFB_TEMPLATE}" ]; then
    echo "==> Enabling template ${XVFB_TEMPLATE}"

    cp "/etc/consul-template/templates/xvfb/${XVFB_TEMPLATE}"/*.hcl /etc/consul-template/conf.d/
fi
