version: '3.5'

volumes:
    mail:
    postfix:

services:
    dovecot:
        image: bhuisgen/alpine-dovecot
        ports:
            #- "110:110"        # POP3
            #- "143:143"        # IMAP
            - "993:993"         # IMAPS
            - "995:995"         # POP3S
            #- "24:24"          # LMTP
            #- "12345:12345"    # SASL AUTH
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - postfix:/var/spool/postfix            # volume of postfix spool
            - mail:/var/mail                        # volume for mail storage
        environment:
            - ENV=local                             # environment name
            #- VAULT_ADDR=                          # vault address
            #- VAULT_TLS=1                          # enable TLS
            #- VAULT_TOKEN=                         # vault token
            #- VAULT_SECRET=local/openldap/         # secret path
            #- CONSUL_ADDR=                         # consul address
            #- CONSUL_SERVICENAME=dovecot           # consul service name
            #- CONSUL_SERVICETAGS=local             # consul service tag
            #- CONSUL_SERVICEPORT=143               # consul service port
            #- CONSUL_CHECKTYPE=tcp                 # consul health check type
            - DOVECOT_TEMPLATE=ldap                 # configuration template

            #
            # template ldap
            #

            #- DOVECOT_PROTOCOLS=imap pop3 lmtp                   # protocols to serve
            #- DOVECOT_INSTANCENAME=dovecot                       # instance name
            #- DOVECOT_LOGINGREETING=Dovecot ready.               # login greeting
            #- DOVECOT_LOGINTRUSTEDNETWORKS=                      # trusted networks list
            #- DOVECOT_DICTQUOTA=                                 # dict quota
            #- DOVECOT_DICTEXPIRE=                                # dict expire
            #- DOVECOT_DICTACL=                                   # dict ACL
            #- DOVECOT_MAILLOCATION=                              # mail location
            #- DOVECOT_DEFAULTPROCESSLIMIT=                       # default connections limit
            #- DOVECOT_DEFAULTCLIENTLIMIT=                        # default clients limit
            #- DOVECOT_IMAPLOGINPROCESSMINAVAIL=                  # number of processes to keep waiting for imap login connections
            #- DOVECOT_IMAPPROCESSLIMIT=                          # imap connections limit
            #- DOVECOT_POP3PROCESSLIMIT=                          # pop3 connections limit
            #- DOVECOT_SSL=yes                                    # enable SSL/TLS (yes/no/required)
            #- DOVECOT_SSLCERT=                                   # TLS certificate file
            #- DOVECOT_SSLKEY=                                    # TLS key file
            #- DOVECOT_SSLPROTOCOLS=!SSLv3                        # TLS protocols
            #- DOVECOT_SSLCIPHERLIST=ALL:!LOW:!SSLv2:!EXP:!aNULL  # TLS cipher list
            #- DOVECOT_POSTMASTERADDRESS=                         # postmaster address
            - DOVECOT_LDAPSERVICENAME=openldap                    # consul service name of LDAP backend
            - DOVECOT_LDAPSERVICETAG=local                        # consul service tag of LDAP backend
            #- DOVECOT_DN=                                        # LDAP DN
            #- DOVECOT_DNPASS=                                    # LDAP password
            #- DOVECOT_TLS=0                                      # enable LDAP TLS
            #- DOVECOT_TLSCACERTFILE=                             # TLS CA certificate file
            #- DOVECOT_TLSCACERTDIR=                              # TLS CA certificates directory
            #- DOVECOT_TLSCIPHERSUITE=                            # TLS cipher suite
            #- DOVECOT_TLSCERTFILE=                               # TLS client certificate file
            #- DOVECOT_TLSKEYFILE=                                # TLS client key file
            #- DOVECOT_TLSREQUIRECERT=                            # TLS require certificate
            #- DOVECOT_AUTHBIND=                                  # LDAP auth bind
            #- DOVECOT_AUTHBINDUSERDN=                            # LDAP auth bind user DN
            #- DOVECOT_BASE=                                      # LDAP base
            #- DOVECOT_SCOPE=                                     # LDAP scope
            #- DOVECOT_USERATTRS=                                 # LDAP user attributes
            #- DOVECOT_USERFILTER=                                # LDAP user filter
            #- DOVECOT_PASSATTRS=                                 # LDAP pass attributes
            #- DOVECOT_PASSFILTER=                                # LDAP pass filter
            #- DOVECOT_ITERATEATTRS=                              # LDAP iterate attributes
            #- DOVECOT_ITERATEFILTER=                             # LDAP iterate filter
            #- DOVECOT_DEFAULTPASSSCHEME=                         # LDAP default pass scheme
