version: '3.7'

volumes:
    mail:
    postfix:

services:
    dovecot:
        image: bhuisgen/alpine-dovecot
        ports:
            #- "110:110"        # POP3
            #- "143:143"        # IMAP
            - "993:993"         # IMAPS
            - "995:995"         # POP3S
            #- "24:24"          # LMTP
            #- "12345:12345"    # SASL AUTH
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - postfix:/var/spool/postfix            # volume of postfix spool
            - mail:/var/mail                        # volume for mail storage
        environment:
            - ENV=local                             # environment name
            #- DOVECOT_TEMPLATE=ldap                # configuration template

            #
            # template ldap
            #

            #- DOVECOT_PROTOCOLS=imap pop3 lmtp                   # protocols to serve
            #- DOVECOT_INSTANCENAME=dovecot                       # instance name
            #- DOVECOT_LOGINGREETING=Dovecot ready.               # login greeting
            #- DOVECOT_LOGINTRUSTEDNETWORKS=                      # trusted networks list
            #- DOVECOT_DICTQUOTA=                                 # dict quota
            #- DOVECOT_DICTEXPIRE=                                # dict expire
            #- DOVECOT_DICTACL=                                   # dict ACL
            #- DOVECOT_MAILLOCATION=                              # mail location
            #- DOVECOT_DEFAULTPROCESSLIMIT=                       # default connections limit
            #- DOVECOT_DEFAULTCLIENTLIMIT=                        # default clients limit
            #- DOVECOT_IMAPLOGINPROCESSMINAVAIL=                  # number of processes to keep waiting for imap login connections
            #- DOVECOT_IMAPPROCESSLIMIT=                          # imap connections limit
            #- DOVECOT_POP3PROCESSLIMIT=                          # pop3 connections limit
            #- DOVECOT_SSL=yes                                    # enable SSL/TLS (yes/no/required)
            #- DOVECOT_SSLCERT=                                   # TLS certificate file
            #- DOVECOT_SSLKEY=                                    # TLS key file
            #- DOVECOT_SSLMINPROTOCOL=TLSv1                       # TLS minimal protocol
            #- DOVECOT_SSLCIPHERLIST=ALL:!LOW:!SSLv2:!EXP:!aNULL  # TLS cipher list
            #- DOVECOT_POSTMASTERADDRESS=                         # postmaster address
            #- DOVECOT_LDAPHOSTS=openldap:389                     # LDAP backend hosts
            #- DOVECOT_LDAPDN=                                    # LDAP DN
            #- DOVECOT_LDAPDNPASS=                                # LDAP password
            #- DOVECOT_LDAPTLS=0                                  # enable LDAP TLS
            #- DOVECOT_LDAPTLSCACERTFILE=                         # LDAP TLS CA certificate file
            #- DOVECOT_LDAPTLSCACERTDIR=                          # LDAP TLS CA certificates directory
            #- DOVECOT_LDAPTLSCIPHERSUITE=                        # LDAP TLS cipher suite
            #- DOVECOT_LDAPTLSCERTFILE=                           # LDAP TLS client certificate file
            #- DOVECOT_LDAPTLSKEYFILE=                            # LDAP TLS client key file
            #- DOVECOT_LDAPTLSREQUIRECERT=                        # LDAP TLS require certificate
            #- DOVECOT_LDAPAUTHBIND=                              # LDAP auth bind
            #- DOVECOT_LDAPAUTHBINDUSERDN=                        # LDAP auth bind user DN
            #- DOVECOT_LDAPBASE=                                  # LDAP base
            #- DOVECOT_LDAPSCOPE=                                 # LDAP scope
            #- DOVECOT_LDAPUSERATTRS=                             # LDAP user attributes
            #- DOVECOT_LDAPUSERFILTER=                            # LDAP user filter
            #- DOVECOT_LDAPPASSATTRS=                             # LDAP pass attributes
            #- DOVECOT_LDAPPASSFILTER=                            # LDAP pass filter
            #- DOVECOT_LDAPITERATEATTRS=                          # LDAP iterate attributes
            #- DOVECOT_LDAPITERATEFILTER=                         # LDAP iterate filter
            #- DOVECOT_LDAPDEFAULTPASSSCHEME=                     # LDAP default pass scheme

            #
            # template sql
            #

            #- DOVECOT_PROTOCOLS=imap pop3 lmtp                   # protocols to serve
            #- DOVECOT_INSTANCENAME=dovecot                       # instance name
            #- DOVECOT_LOGINGREETING=Dovecot ready.               # login greeting
            #- DOVECOT_LOGINTRUSTEDNETWORKS=                      # trusted networks list
            #- DOVECOT_DICTQUOTA=                                 # dict quota
            #- DOVECOT_DICTEXPIRE=                                # dict expire
            #- DOVECOT_DICTACL=                                   # dict ACL
            #- DOVECOT_MAILLOCATION=                              # mail location
            #- DOVECOT_DEFAULTPROCESSLIMIT=                       # default connections limit
            #- DOVECOT_DEFAULTCLIENTLIMIT=                        # default clients limit
            #- DOVECOT_IMAPLOGINPROCESSMINAVAIL=                  # number of processes to keep waiting for imap login connections
            #- DOVECOT_IMAPPROCESSLIMIT=                          # imap connections limit
            #- DOVECOT_POP3PROCESSLIMIT=                          # pop3 connections limit
            #- DOVECOT_SSL=yes                                    # enable SSL/TLS (yes/no/required)
            #- DOVECOT_SSLCERT=                                   # TLS certificate file
            #- DOVECOT_SSLKEY=                                    # TLS key file
            #- DOVECOT_SSLMINPROTOCOL=TLSv1                       # TLS minimal protocol
            #- DOVECOT_SSLCIPHERLIST=ALL:!LOW:!SSLv2:!EXP:!aNULL  # TLS cipher list
            #- DOVECOT_POSTMASTERADDRESS=                         # postmaster address
            #- DOVECOT_SQLDRIVER=sqlite                           # SQL driver
            #- DOVECOT_SQLCONNECT=                                # SQL connect options
            #- DOVECOT_SQLDEFAULTPASSSCHEME=MD5                   # SQL default password scheme
            #- DOVECOT_SQLPASSWORDQUERY=                          # SQL password query
            #- DOVECOT_SQLUSERQUERY=                              # SQL user query
            #- DOVECOT_SQLITERATEQUERY=                           # SQL iterate query
            #- DOVECOT_SQLUSERDBSTATICHOME=                       # SQL userdb static home
