version: '3.7'

services:
    backup-mongodb:
        image: bhuisgen/alpine-backup-mongodb
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /srv/backups:/var/backups             # volume for storage
        environment:
            - ENV=local                             # environment name
            #- BACKUP_PATH=/var/backups             # backup storage path
            - BACKUP_MONGODB_HOST=my_host           # server host (required)
            - BACKUP_MONGODB_PORT=27017             # server port (required)
            - BACKUP_MONGODB_DATABASE=dbname        # database to backup (required, comma delimited list)
