#!/usr/bin/env bash

if ls -A /etc/consul-template/conf.d/*.hcl > /dev/null 2>&1; then
    if ! consul-template -config /etc/consul-template/conf.d/ -once ${CONSULTEMPLATE_OPTIONS}; then
        exit 1
    fi
fi
