#!/usr/bin/env bash

if [ -n "${CONSUL_ADDR}" ]; then
    options=""
    consul_addr="http://${CONSUL_ADDR}"

    if [ -n "${CONSUL_TLS}" ] && [ "${CONSUL_TLS}" -eq 1 ]; then
        consul_addr="https://${CONSUL_ADDR}"

        if [ -n "${CONSUL_TLSCAFILE}" ]; then
            options="${options} --cacert ${CONSUL_TLSCAFILE}"
        elif [ -n "${CONSUL_TLSCAPATH}" ]; then
            options="${options} --capath ${CONSUL_TLSCAPATH}"
        fi

        if [ -n "${CONSUL_TLSCERTFILE}" ]; then
            options="${options} --cert ${CONSUL_TLSCERTFILE}"
        fi

        if [ -n "${CONSUL_TLSKEYFILE}" ]; then
            options="${options} --key ${CONSUL_TLSKEYFILE}"
        fi

        if [ -z "${CONSUL_TLSVERIFY}" ] || [ "${CONSUL_TLSVERIFY}" -ne 1 ]; then
            options="${options} --insecure"
        fi
    fi

    if [ -n "${CONSUL_TOKEN}" ]; then
        options="${options} --header X-Consul-Token:${CONSUL_TOKEN}"
    fi

    if [ -n "$1" ] && [ "$1" == "--enable" ]; then
        options="${options} -G --data-urlencode enable=true"
    elif [ -n "$1" ] && [ "$1" == "--disable" ]; then
        options="${options} -G --data-urlencode enable=false"
    else
        exit 1
    fi

    status=0

    if [ -f /var/run/container/service.json ]; then
        serviceid=$(jq -r '.ID' /var/run/container/service.json) && \
            [ $(curl -s -w '%{http_code}' --out /dev/null ${options} \
                -X PUT "${consul_addr}/v1/agent/service/maintenance/${serviceid}") == "200" ] || status=1
    fi

    exit $status
fi
