#!/usr/bin/with-contenv sh

if [ ! -z "${UNBOUND_TEMPLATE}" ]; then
    echo "==> Enabling template ${UNBOUND_TEMPLATE}"

    cp "/etc/consul-template/templates/unbound/${UNBOUND_TEMPLATE}"/*.hcl /etc/consul-template/conf.d/
fi
