#!/command/with-contenv sh

cd /usr/local/portainer || exit 1
exec s6-setuidgid portainer /usr/local/portainer/portainer -d /var/lib/portainer --template-file=./templates.json \
    ${PORTAINER_OPTIONS}
