version: '3.8'

services:
    spark-master:
        image: bhuisgen/alpine-spark
        ports:
            - "4040:4040"
            - "6066:6066"
            - "7077:7077"
            - "8080:8080"
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - ENV=local                                 # environment name

    spark-worker1:
        image: bhuisgen/alpine-spark
        ports:
            - "8081:8081"
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - ENV=local                                 # environment name
            - SPARK_MASTERURL=spark://spark-master:7077 # spark master URL
