#!/usr/bin/with-contenv sh

echo "==> Configuring dnsmasq"

sed -i "s/^interface=.*$/interface=${DNSMASQ_INTERFACE}/" /etc/dnsmasq.conf
sed -i "s/^dhcp-range=.*$/dhcp-range=${DNSMASQ_DHCPRANGE}/" /etc/dnsmasq.conf
sed -i "s/^dhcp-option=option:netmask,.*$/dhcp-option=option:netmask,${DNSMASQ_DHCPNETMASK}/" /etc/dnsmasq.conf
sed -i "s/^dhcp-option=option:router,.*$/dhcp-option=option:router,${DNSMASQ_DHCPROUTER}/" /etc/dnsmasq.conf
sed -i "s/^dhcp-option=option:ntp-server,.*$/dhcp-option=option:ntp-server,${DNSMASQ_DHCPNTPSERVER}/" /etc/dnsmasq.conf
