version: '3.5'

services:
    backup-postgresql:
        depends_on:
            - consul                                # consul agent
        image: bhuisgen/alpine-backup-postgresql
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /srv/backups:/var/backups             # volume for storage
        environment:
            - ENV=local                             # environment name
            - CONSUL_AGENT=consul                   # consul agent hostname/IP
            #- CONSUL_PORT=8500                     # consul agent port
            #- CONSUL_KEYPREFIX=path/prefix/        # consul key prefix path
            #- BACKUP_PATH=/var/backups             # backup storage path
            - BACKUP_POSTGRESQL_HOST=server         # server host (required)
            - BACKUP_POSTGRESQL_PORT=5432           # server port (required)
            #- BACKUP_POSTGRESQL_DATABASE=          # databases to backup (optional, comma delimited list)
