version: '3.7'

volumes:
    openssh:

services:
    openssh:
        image: bhuisgen/alpine-openssh
        ports:
            - "2222:22"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - openssh:/home                             # volume for data
        environment:
            - ENV=local                                 # environment name
            #- OPENSSH_TEMPLATE=generic                 # configuration template

            #
            # template generic
            #

            #- OPENSSH_PASSWORDAUTHENTICATION=no        # enable authentication by password
            #- OPENSSH_SFTPUSERS=                       # SFTP users to create (comma separated list)
            #- OPENSSH_SFTPGROUP=sftp                   # SFTP group for users
            #- OPENSSH_SFTPGID=101                      # GID of SFTP group
            #- OPENSSH_SFTPCHROOT=1                     # enable chroot for SFTP
            #- OPENSSH_SFTPCHROOTUSERDIR=public_html    # user directory inside chroot
