version: '3.5'

volumes:
    openssh:

services:
    openssh:
        depends_on:
            - consul                                    # consul agent
        image: bhuisgen/alpine-openssh
        ports:
            - "2222:22"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - openssh:/home                             # volume for data
        environment:
            - ENV=local                                 # environment name
            - CONSUL_AGENT=consul                       # consul agent hostname/IP
            #- CONSUL_PORT=8500                         # consul agent port
            #- CONSUL_KEYPREFIX=path/prefix/            # consul key prefix path
            - CONSUL_SERVICENAME=openssh                # consul service name
            - CONSUL_SERVICETAGS=local                  # consul service tag
            - CONSUL_SERVICEPORT=22                     # consul service port
            - CONSUL_CHECKTYPE=tcp                      # consul health check type
            #- OPENSSH_PASSWORDAUTHENTICATION=no        # enable authentication by password
            #- OPENSSH_SFTPUSERS=                       # SFTP users to create (comma separated list)
            #- OPENSSH_SFTPGROUP=sftp                   # SFTP group for users
            #- OPENSSH_SFTPGID=101                      # GID of SFTP group
            #- OPENSSH_SFTPCHROOT=1                     # enable chroot for SFTP
            #- OPENSSH_SFTPCHROOTUSERDIR=public_html    # user directory inside chroot
