version: '3.7'

networks:
    default:
        external:
            name: backend

services:
    backup-mariadb:
        image: bhuisgen/alpine-backup-mariadb
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /srv/backups:/var/backups             # storage path
        environment:
            - ENV=local                             # environment name
            #- BACKUP_PATH=/var/backups             # backup path
            #- BACKUP_MARIADB_HOST=mariadb          # server host
            #- BACKUP_MARIADB_PORT=3306             # server port
            #- BACKUP_MARIADB_DATABASE=             # database to backup (optional, comma delimited list)
            #- BACKUP_ROTATE=1                      # enable backup files rotation
            #- BACKUP_ROTATE_DAYS=4                 # number of backup to keep in days
