version: '3.7'

services:
    backup-mariadb:
        image: bhuisgen/alpine-backup-mariadb
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /srv/backups:/var/backups             # volume for storage
        environment:
            - ENV=local                             # environment name
            #- BACKUP_PATH=/var/backups             # backup storage path
            - BACKUP_MARIADB_HOST=server            # server host (required)
            - BACKUP_MARIADB_PORT=3306              # server port (required)
            #- BACKUP_MARIADB_DATABASE=             # database to backup (optional, comma delimited list)
