#!/usr/bin/with-contenv sh

echo "==> Configuring hostapd"

sed -i "s/^interface=.*$/interface=${HOSTAPD_INTERFACE}/"  /etc/hostapd/hostapd.conf
sed -i "s/^ssid=.*$/ssid=${HOSTAPD_SSID}/" /etc/hostapd/hostapd.conf
sed -i "s/^wpa_passphrase=.*$/wpa_passphrase=${HOSTAPD_WPAPASSPHRASE}/" /etc/hostapd/hostapd.conf
