#!/usr/bin/with-contenv sh

if [ -z ${POSTGRESQL_CONFIG} ]; then
    echo "==> Configuring postgresql"

    su -c "initdb ${PGDATA}" postgres

    su -c "pg_ctl start" postgres
    sleep 4

    if [ ! -z ${POSTGRESQL_DATABASE} ] && [ ! -z ${POSTGRESQL_USERNAME} ] && [ ! -z ${POSTGRESQL_PASSWORD} ] && [ ! -z ${POSTGRESQL_ADDRESS} ]; then
        echo "==> Creating database and user"
        su -c "createuser ${POSTGRESQL_USERNAME}" postgres
        su -c "createdb -O${POSTGRESQL_USERNAME} ${POSTGRESQL_DATABASE}" postgres
        su -c "psql -c \"ALTER USER ${POSTGRESQL_USERNAME} WITH PASSWORD '${POSTGRESQL_PASSWORD}';\"" postgres
        echo "host ${POSTGRESQL_DATABASE} ${POSTGRESQL_USERNAME} ${POSTGRESQL_ADDRESS} md5" >> "${PGDATA}/pg_hba.conf"
        su -c "pg_ctl reload" postgres
        sleep 4
    fi

    if [ ! -z ${POSTGRESQL_CONFIGSCRIPT} ]; then
        /bin/sh ${POSTGRESQL_CONFIGSCRIPT}
    fi

    su -c "pg_ctl stop" postgres
    sleep 4

    export POSTGRESQL_CONFIG=1
    printf "%s" "${POSTGRESQL_CONFIG}" > /var/run/s6/container_environment/POSTGRESQL_CONFIG
fi
