version: '3.7'

services:
    kibana:
        image: bhuisgen/alpine-kibana
        ports:
            - "5601:5601"
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - ENV=local                             # environment name
            #- KIBANA_TEMPLATE=generic              # configuration template

            #
            # template generic
            #

            #- KIBANA_ELASTICSEARCHURL=http://elasticsearch:9200    # elasticsearch URL
