version: '3.7'

volumes:
    logstash:

services:
    logstash:
        image: bhuisgen/alpine-logstash
        ports:
            - "9600:9600"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - logstash:/var/lib/logstash            # volume for data
        environment:
            - ENV=local                             # environment name
            - LOGSTASH_TEMPLATE=generic             # configuration template

            #
            # template generic
            #

            #- LOGSTASH_ELASTICSEARCH=elasticsearch # elastic server (comma delimited list)
            #- LOGSTASH_JVMHEAPSIZE=1g              # JVM heap size
