version: '3.5'

volumes:
    logstash:

services:
    logstash:
        depends_on:
            - consul                                # consul agent
        image: bhuisgen/alpine-logstash
        ports:
            - "10514:10514"
            - "10514:10514/udp"
            - "12201:12201/udp"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - logstash:/var/lib/logstash            # volume for data
        environment:
            - ENV=local                             # environment name
            - CONSUL_AGENT=consul                   # consul agent hostname/IP
            #- CONSUL_PORT=8500                     # consul agent port
            #- CONSUL_KEYPREFIX=path/prefix/        # consul key prefix path
            - CONSUL_SERVICENAME=logstash           # consul service name
            - CONSUL_SERVICETAGS=local              # consul service tag
            - CONSUL_SERVICEPORT=10514              # consul service port
            - CONSUL_CHECKTYPE=tcp                  # consul health check type
            #- LOGSTASH_TEMPLATE=                   # configuration template
            #
            # template cluster
            #
            - LOGSTASH_TEMPLATE_CLUSTER_SERVICENAME=elasticsearch   # consul service name
            - LOGSTASH_TEMPLATE_CLUSTER_SERVICETAG=local            # consul service tag
