pipeline:
    build-prod:
        when:
            branch:
                include: [ master ]
        image: alpine:3.9
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - apk add --update build-base autoconf automake docker
            - ./autogen.sh
            - ./configure TAG=prod
            - make build

    build-dev:
        when:
            branch:
                exclude: [ master ]
        image: alpine:3.9
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - apk add --update build-base autoconf automake docker
            - ./autogen.sh
            - ./configure TAG=dev
            - make build
