version: '3.5'

services:
    tomcat:
        depends_on:
            - consul                                # consul agent
        image: bhuisgen/alpine-tomcat
        ports:
            - "8080:8080"
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - ENV=local                             # environment name
            - CONSUL_AGENT=consul                   # consul agent hostname/IP
            #- CONSUL_PORT=8500                     # consul agent port
            #- CONSUL_KEYPREFIX=path/prefix/        # consul key prefix path
            - CONSUL_SERVICENAME=tomcat             # consul service name
            - CONSUL_SERVICETAGS=local              # consul service tag
            - CONSUL_SERVICEPORT=8080               # consul service port
            - CONSUL_CHECKTYPE=tcp                  # consul health check type
            #- TOMCAT_DEBUG=0                       # enable JVM debug
            #- TOMCAT_JDWP=0                        # enable JVM remote debug
            #- TOMCAT_JMX=0                         # enable JMX monitoring
            #- TOMCAT_JMXAUTH=0                     # enable JMX authentication
            #- TOMCAT_JMXUSERNAME=tomcat            # JMX username
            #- TOMCAT_JMXPASSWORD=tomcat            # JMX password
            #- TOMCAT_JMXSSL=0                      # enable SSL protocol for JMX
            #- TOMCAT_JMXSSLKEYSTORE=/usr/local/tomcat/conf/keystore.jks        # JMX SSL keystore file
            #- TOMCAT_JMXSSLKEYSTOREPASSWORD=mysecret                           # JMX SSL keystore password
            #- TOMCAT_JMXSSLTRUSTSTORE=/usr/local/tomcat/conf/truststore.jks    # JMX SSL truststore file
            #- TOMCAT_JMXSSLTRUSTSTOREPASSWORD=mysecret                         # JMX SSL truststore password
