version: '3.8'

services:
    tomcat:
        image: bhuisgen/alpine-tomcat
        ports:
            - "8080:8080"
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - ENV=local                             # environment name
            #- TOMCAT_TEMPLATE=generic              # configuration template

            #
            # template generic
            #

            #- TOMCAT_DEBUG=0                       # enable JVM debug
            #- TOMCAT_JDWP=0                        # enable JVM remote debug
            #- TOMCAT_JMX=0                         # enable JMX monitoring
            #- TOMCAT_JMXAUTH=0                     # enable JMX authentication
            #- TOMCAT_JMXUSERNAME=tomcat            # JMX username
            #- TOMCAT_JMXPASSWORD=tomcat            # JMX password
            #- TOMCAT_JMXSSL=0                      # enable SSL protocol for JMX
            #- TOMCAT_JMXSSLKEYSTORE=/usr/local/tomcat/conf/keystore.jks        # JMX SSL keystore file
            #- TOMCAT_JMXSSLKEYSTOREPASSWORD=mysecret                           # JMX SSL keystore password
            #- TOMCAT_JMXSSLTRUSTSTORE=/usr/local/tomcat/conf/truststore.jks    # JMX SSL truststore file
            #- TOMCAT_JMXSSLTRUSTSTOREPASSWORD=mysecret                         # JMX SSL truststore password
