#!/usr/bin/with-contenv sh

if [ ! -z "${CONTAINER_WAITFOR_HOST}" ] && [ ! -z "${CONTAINER_WAITFOR_PORT}" ] ; then
    while true; do
        nc -z "${CONTAINER_WAITFOR_HOST}" "${CONTAINER_WAITFOR_PORT}" > /dev/null 2>&1 && break

        sleep 15
    done
fi
