#!/usr/bin/with-contenv sh

java_opts="
        -Des.path.home=/var/lib/elasticsearch
        -Des.default.path.plugins=/var/lib/elasticsearch/plugins
        -Des.default.path.work=/var/lib/elasticsearch/tmp
        -Des.default.path.script=/var/lib/elasticsearch/bin
        ${JAVA_OPTS}
        "
elastic_opts="
        -Epath.data=/var/lib/elasticsearch/data
        -Epath.logs=/var/lib/elasticsearch/logs
        ${ELASTICSEARCH_OPTIONS}
        "

export ES_JAVA_OPTS="$java_opts"
export ES_JVM_OPTIONS="/usr/local/elasticsearch/config/jvm.options"
export ES_TMPDIR=/var/lib/elasticsearch/tmp

cd /usr/local/elasticsearch || exit 1
exec s6-setuidgid elasticsearch /usr/local/elasticsearch/bin/elasticsearch ${elastic_opts}
