#!/usr/bin/with-contenv sh

if [ ! -z ${CONSULUI_USERNAME} ] && [ ! -z ${CONSULUI_PASSWORD} ]; then
    echo "==> Creating consul UI user credentials"

    printf "%s:%s\n" ${CONSULUI_USERNAME} "$(openssl passwd -crypt ${CONSULUI_PASSWORD})" > "/etc/nginx/consului.htpasswd"
    chown root:nginx "/etc/nginx/consului.htpasswd"
    chmod 440 "/etc/nginx/consului.htpasswd"
fi
