version: '3.7'

volumes:
    etcd:

services:
    etcd:
        image: bhuisgen/alpine-etcd
        ports:
            - "2379:2379"
            - "2380:2380"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - etcd:/var/lib/etcd                        # volume for data
        environment:
            - ENV=local                                 # environment name
