#!/usr/bin/with-contenv sh

echo "==> Cleaning iptables"

sysctl -w net.ipv4.ip_forward=0

iptables -D INPUT -i "${STRONGSWAN_INTERFACE}" -p udp --dport 500 -j ACCEPT
iptables -D INPUT -i "${STRONGSWAN_INTERFACE}" -p udp --dport 4500 -j ACCEPT
iptables -D FORWARD -j ACCEPT
iptables -D OUTPUT -o "${STRONGSWAN_INTERFACE}" -p udp --dport 500 -j ACCEPT
iptables -D OUTPUT -o "${STRONGSWAN_INTERFACE}" -p udp --dport 4500 -j ACCEPT
