version: '3.7'

services:
    python:
        image: bhuisgen/alpine-python
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - ENV=local                             # environment name
