#!/usr/bin/with-contenv sh

if [ -z ${RABBITMQ_CONFIG} ]; then
    echo "==> Configuring rabbitmq"
    /usr/local/rabbitmq/sbin/rabbitmq-server -detached
    sleep 4
    /usr/local/rabbitmq/sbin/rabbitmqctl start_app
    sleep 1

    if [ ! -z ${RABBITMQ_GUESTPASSWORD} ]; then
        /usr/local/rabbitmq/sbin/rabbitmqctl change_password guest ${RABBITMQ_GUESTPASSWORD}
    fi

    if [ ! -z ${RABBITMQ_USERNAME} ] && [ ! -z ${RABBITMQ_PASSWORD} ]; then
        /usr/local/rabbitmq/sbin/rabbitmqctl add_user ${RABBITMQ_USERNAME} ${RABBITMQ_PASSWORD}
        /usr/local/rabbitmq/sbin/rabbitmqctl set_user_tags ${RABBITMQ_USERNAME} administrator
        /usr/local/rabbitmq/sbin/rabbitmqctl set_permissions -p / ${RABBITMQ_USERNAME} ".*" ".*" ".*"
    fi

    /usr/local/rabbitmq/sbin/rabbitmqctl stop_app
    sleep 1
    /usr/local/rabbitmq/sbin/rabbitmqctl stop
    sleep 4

    export RABBITMQ_CONFIG=1
    printf "%s" "${RABBITMQ_CONFIG}" > /var/run/s6/container_environment/RABBITMQ_CONFIG
fi
