version: '3.7'

services:
    java:
        image: bhuisgen/alpine-java
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - ENV=local                             # environment name
