version: '3.2'

services:
    consul:
        image: bhuisgen/alpine-consul
        ports:
            - "8500:8500"
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - CONSUL_OPTIONS=-server -bootstrap-expect 1 -client 0.0.0.0 -ui    # minimal server options

    postgresql:
        depends_on:
            - consul
        image: bhuisgen/alpine-postgresql
        ports:
            - "5432:5432"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            #- /host/data:/var/lib/postgresql                       # volume for data
        environment:
            - CONSUL_AGENT=consul                                   # consul agent hostname/IP
            #- CONSUL_PORT=8500                                     # consul agent port
            #- CONSUL_KEYPREFIX=path/prefix/                        # consul key prefix path
            - CONSUL_SERVICENAME=postgresql                         # consul service name
            - CONSUL_SERVICETAGS=dev                                # consul service tag
            - CONSUL_SERVICEPORT=5432                               # consul service port
            - CONSUL_CHECKTYPE=tcp                                  # consul health check type
            #- POSTGRESQL_DATABASE=                                 # create database (optional)
            #- POSTGRESQL_USERNAME=                                 # grant user name (optional)
            #- POSTGRESQL_PASSWORD=                                 # grant user password (optional)
            #- POSTGRESQL_ADDRESS=                                  # grant user address (optional)
            #- POSTGRESQL_CONFIGSCRIPT=/root/postgresql/config.sh   # custom configuration script
