version: '3.8'

volumes:
    postgresql:

services:
    postgresql:
        image: bhuisgen/alpine-postgresql
        ports:
            - "5432:5432"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - postgresql:/var/lib/postgresql        # volume for data
        environment:
            - ENV=local                             # environment name
            #- POSTGRESQL_TEMPLATE=generic          # configuration template

            #
            # template generic
            #

            #- POSTGRESQL_DATABASE=                 # create database (optional)
            #- POSTGRESQL_USERNAME=                 # database user name
            #- POSTGRESQL_PASSWORD=                 # database user password
            #- POSTGRESQL_ADDRESS=                  # source address mask allowed for this user
            #- POSTGRESQL_CREATEDB=0                # enable user to create new databases
            #- POSTGRESQL_ALLOWALL=0                # enable user to access to all databases
