version: '3.5'

volumes:
    consul:

services:
    consul:
        image: bhuisgen/alpine-consul
        ports:
            - "8300:8300"       # server RPC
            - "8301:8301"       # serf LAN
            - "8301:8301/udp"   # serf LAN (UDP)
            - "8302:8302"       # serf WAN
            - "8302:8302/udp"   # serf WAN (UDP)
            - "8500:8500"       # HTTP
            - "8501:8501"       # HTTPS
            - "8600:8600"       # DNS
            - "8600:8600/udp"   # DNS (UDP)
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - consul:/var/lib/consul                    # volume for data
        environment:
            - ENV=local                                 # environment name
            - CONSUL_OPTIONS=-server -bootstrap-expect 1 -client 0.0.0.0 -ui    # server mode with UI
            - CONSUL_DATACENTER=local                   # datacenter
            - CONSUL_DOMAIN=consul                      # domain name
            - CONSUL_ENCRYPT=h2N6R1eyTysjBzzXxAWJvA==   # encryption key
            #- CONSUL_TLS=0                             # enable TLS
            #- CONSUL_TLSCAFILE=                        # TLS CA certificate file
            #- CONSUL_TLSCERTFILE=                      # TLS server certificate file (server)
            #- CONSUL_TLSKEYFILE=                       # TLS server certificate key file (server)
            #- CONSUL_ACLDATACENTER=                    # ACL authoritative datacenter
            #- CONSUL_ACLMASTERTOKEN=                   # ACL master token (server only)
            #- CONSUL_ACLTOKEN=                         # ACL token
            #- CONSUL_ACLAGENTMASTERTOKEN=              # ACL token during server outage (client only)
            #- CONSUL_ACLAGENTTOKEN=                    # ACL token for internal operations (client only, ACL token by default)
            #- CONSUL_ACLREPLICATIONTOKEN=              # ACL token for replication outside of datacenter (server only)
            #- CONSUL_ACLDEFAULTPOLICY=extend-cache     # ACL default policy (server only)
            #- CONSUL_ACLDOWNPOLICY=extend-cache        # ACL down policy
            #- CONSUL_ACLTTL=30                         # ACL TTL (server only)
            #- CONSUL_ACLENFORCEVERSION8=true           # Enforce ACL version 8
            #- CONSUL_RAFTMULTIPLIER=0                  # Raft mutliplier
