FROM bhuisgen/alpine-base-consul:latest
MAINTAINER Boris HUISGEN <bhuisgen@hbis.fr>

COPY root /

ENTRYPOINT ["/init"]
CMD []

EXPOSE 8300/tcp 8301/tcp 8301/udp 8302/tcp 8302/udp 8400/tcp 8500/tcp 8600/tcp 8600/udp
