version: '3.7'

volumes:
    consul:

services:
    consul:
        image: bhuisgen/alpine-consul
        network_mode: host
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - consul:/var/lib/consul                    # volume for data
        environment:
            - ENV=local                                 # environment name
            #- VAULT_ADDR=                              # vault address
            #- VAULT_TOKEN=                             # vault token
            #- VAULT_SECRET=                            # vault secret path
            - CONSUL_TEMPLATE=generic                   # configuration template

            #
            # template generic
            #

            - CONSUL_OPTIONS=-advertise {{GetPrivateIP}} -retry-join server.my.domain -client 169.254.0.1   # client mode
            #- CONSUL_NODENAME=                         # node name
            - CONSUL_DATACENTER=local                   # datacenter
            #- CONSUL_DOMAIN=consul                     # domain name
            - CONSUL_ENCRYPT=h2N6R1eyTysjBzzXxAWJvA==   # encryption key
            #- CONSUL_RAFTMULTIPLIER=5                  # raft mutliplier
            #- CONSUL_TLS=0                             # enable TLS
            #- CONSUL_TLSCAPATH=                        # TLS CA directory
            #- CONSUL_TLSCAFILE=                        # TLS CA certificate file
            #- CONSUL_TLSCERTFILE=                      # TLS client certificate file
            #- CONSUL_TLSKEYFILE=                       # TLS client certificate key file
            #- CONSUL_ACLPRIMARYDATACENTER=             # ACL primary datacenter
            #- CONSUL_ACLDOWNPOLICY=extend-cache        # ACL down policy
            #- CONSUL_ACLTOKENDEFAULT=                  # ACL default token
            #- CONSUL_ACLTOKENAGENTMASTER=              # ACL agent master token
            #- CONSUL_ACLTOKENAGENT=                    # ACL agent token
