version: '3.5'

services:
    consul:
        image: bhuisgen/alpine-consul
        network_mode: host
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - ENV=local                                 # environment name
            - CONSUL_OPTIONS=-advertise {{GetPrivateIP}} -retry-join server.my.domain -client 0.0.0.0   # client mode
            - CONSUL_DATACENTER=local                   # datacenter
            - CONSUL_DOMAIN=consul                      # domain name
            - CONSUL_ENCRYPT=h2N6R1eyTysjBzzXxAWJvA==   # encryption key
            #- CONSUL_TLS=0                             # enable TLS
            #- CONSUL_TLSCAFILE=                        # TLS CA certificate file
            #- CONSUL_TLSCERTFILE=                      # TLS server certificate file (server)
            #- CONSUL_TLSKEYFILE=                       # TLS server certificate key file (server)
