version: '3.7'

volumes:
    consul:

services:
    consul:
        image: bhuisgen/alpine-consul
        ports:
            - "8300:8300"       # server RPC
            - "8301:8301"       # serf LAN
            - "8301:8301/udp"   # serf LAN (UDP)
            - "8302:8302"       # serf WAN
            - "8302:8302/udp"   # serf WAN (UDP)
            - "8500:8500"       # HTTP
            - "8501:8501"       # HTTPS
            - "8600:8600"       # DNS
            - "8600:8600/udp"   # DNS (UDP)
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - consul:/var/lib/consul                    # volume for data
        environment:
            - ENV=local                                 # environment name
            #- VAULT_ADDR=                              # vault address
            #- VAULT_TOKEN=                             # vault token
            #- VAULT_SECRET=                            # vault secret path
            - CONSUL_TEMPLATE=generic                   # configuration template

            #
            # template generic
            #

            - CONSUL_OPTIONS=-server -bootstrap-expect 1 -client 0.0.0.0 -ui    # server mode with UI
            - CONSUL_DATACENTER=local                   # datacenter
            #- CONSUL_NODENAME=                         # node name
            #- CONSUL_DOMAIN=consul                     # domain name
            - CONSUL_ENCRYPT=h2N6R1eyTysjBzzXxAWJvA==   # encryption key
            #- CONSUL_RAFTMULTIPLIER=5                  # raft mutliplier
            #- CONSUL_TLS=0                             # enable TLS
            #- CONSUL_TLSCAPATH=                        # TLS CA directory
            #- CONSUL_TLSCAFILE=                        # TLS CA certificate file
            #- CONSUL_TLSCERTFILE=                      # TLS server certificate file
            #- CONSUL_TLSKEYFILE=                       # TLS server certificate key file
            #- CONSUL_ACLPRIMARYDATACENTER=             # ACL primary datacenter
            #- CONSUL_ACLDOWNPOLICY=extend-cache        # ACL down policy
            #- CONSUL_ACLTOKENTTL=30                    # ACL token TTL
            #- CONSUL_ACLTOKENMASTER=                   # ACL master token
            #- CONSUL_ACLTOKENDEFAULT=                  # ACL default token
            #- CONSUL_ACLTOKENAGENTMASTER=              # ACL agent master token
            #- CONSUL_ACLTOKENAGENT=                    # ACL agent token
            #- CONSUL_ACLTOKENREPLICATION=              # ACL replication token
