#!/usr/bin/with-contenv sh

if [ -z "$CONSULTEMPLATE_ENVIRONMENT" ]; then
    export CONSULTEMPLATE_ENVIRONMENT=1
    printf "%s" "${CONSULTEMPLATE_ENVIRONMENT}" > /var/run/s6/container_environment/CONSULTEMPLATE_ENVIRONMENT
fi

if [ "${CONSULTEMPLATE_ENVIRONMENT}" -eq 1 ]; then
    echo "==> Configuring container from environment"

    options="-config /etc/consul-template/conf-env.d -once"

    if [ ! -z "${CONSULTEMPLATE_OPTIONS}" ]; then
        options="${options} ${CONSULTEMPLATE_OPTIONS}"
    fi

    consul-template ${options}
    if [ $? -ne 0 ]; then
        echo "Failed to configure container from environment, aborting" >&2
        exit 1
    fi
fi
