#!/usr/bin/with-contenv sh

if [ -z $CONSULTEMPLATE_CONTAINER ]; then
    export CONSULTEMPLATE_CONTAINER=1
    printf "%s" "${CONSULTEMPLATE_CONTAINER}" > /var/run/s6/container_environment/CONSULTEMPLATE_CONTAINER
fi

if [ -z $CONSULTEMPLATE_SERVICES ]; then
    export CONSULTEMPLATE_SERVICES=1
    printf "%s" "${CONSULTEMPLATE_SERVICES}" > /var/run/s6/container_environment/CONSULTEMPLATE_SERVICES
fi

if [ ! -z ${CONSUL_AGENT} ] && [ ${CONSULTEMPLATE_CONTAINER} -eq 1 ]; then
    echo "==> Creating container configuration"

    options="-consul ${CONSUL_AGENT}:${CONSUL_PORT}"

    if [ ! -z ${CONSUL_TLS} ] && [ ${CONSUL_TLS} -eq 1 ]; then
        options="${options} -ssl"
    fi

    if [ ! -z ${CONSUL_TOKEN} ]; then
        options="${options} -token ${CONSUL_TOKEN}"
    fi

    options="${options} -config /etc/consul-template/conf-cont.d -once"

    if [ ! -z ${CONSULTEMPLATE_OPTIONS} ]; then
        options="${options} ${CONSULTEMPLATE_OPTIONS}"
    fi

    retry=0
    while true; do
        consul-template ${options} && break
        retry=$((retry+1))
        if [ $retry -lt 3 ]; then
            echo "Failed to create container configuration, retrying in few seconds" >&2
            sleep 15
            continue
        fi

        echo "Failed to create container configuration, aborting" >&2
        exit 1
    done
fi
