#!/usr/bin/with-contenv sh

if [ -z "$CONSULTEMPLATE_ENVIRONMENT" ]; then
    export CONSULTEMPLATE_ENVIRONMENT=1
    printf "%s" "${CONSULTEMPLATE_ENVIRONMENT}" > /var/run/s6/container_environment/CONSULTEMPLATE_ENVIRONMENT
fi

if [ -z "$CONSULTEMPLATE_CONSUL" ]; then
    export CONSULTEMPLATE_CONSUL=1
    printf "%s" "${CONSULTEMPLATE_CONSUL}" > /var/run/s6/container_environment/CONSULTEMPLATE_CONSUL
fi

if [ -z "$CONSULTEMPLATE_SERVICES" ]; then
    export CONSULTEMPLATE_SERVICES=1
    printf "%s" "${CONSULTEMPLATE_SERVICES}" > /var/run/s6/container_environment/CONSULTEMPLATE_SERVICES
fi

if [ "${CONSULTEMPLATE_ENVIRONMENT}" -eq 1 ]; then
    echo "==> Configuring container from environment"

    options="-config /etc/consul-template/conf-env.d -once"

    if [ ! -z "${CONSULTEMPLATE_OPTIONS}" ]; then
        options="${options} ${CONSULTEMPLATE_OPTIONS}"
    fi

    consul-template ${options}
    if [ $? -ne 0 ]; then
        echo "Failed to configure container from environment, aborting" >&2
        exit 1
    fi
fi

if [ ! -z "${CONSUL_AGENT}" ] && [ "${CONSULTEMPLATE_CONSUL}" -eq 1 ]; then
    echo "==> Configuring container from consul"

    options="-config /etc/consul-template/conf-cont.d -once -consul-addr ${CONSUL_AGENT}:${CONSUL_PORT}"

    if [ ! -z "${CONSUL_TLS}" ] && [ "${CONSUL_TLS}" -eq 1 ]; then
        options="${options} -consul-ssl"

        if [ ! -z "${CONSUL_TLSCAFILE}" ]; then
            options="${options} -consul-ssl-ca-cert ${CONSUL_TLSCAFILE}"
        fi

        if [ ! -z "${CONSUL_TLSCERTFILE}" ]; then
            options="${options} -consul-ssl-cert ${CONSUL_TLSCERTFILE}"
        fi

        if [ ! -z "${CONSUL_TLSKEYFILE}" ]; then
            options="${options} -consul-ssl-key ${CONSUL_TLSKEYFILE}"
        fi

        if [ ! -z "${CONSUL_TLSSERVERNAME}" ]; then
            options="${options} -consul-ssl-server-name ${CONSUL_TLSSERVERNAME}"
        fi

        if [ ! -z "${CONSUL_TLSVERIFY}" ] && [ "${CONSUL_TLSVERIFY}" -eq 1 ]; then
            options="${options} -consul-ssl-verify"
        fi
    fi

    if [ ! -z "${CONSUL_TOKEN}" ]; then
        options="${options} -consul-token ${CONSUL_TOKEN}"
    fi

    if [ ! -z "${CONSULTEMPLATE_OPTIONS}" ]; then
        options="${options} ${CONSULTEMPLATE_OPTIONS}"
    fi

    consul-template ${options}
    if [ $? -ne 0 ]; then
        echo "Failed to configure container from consul, aborting" >&2
        exit 1
    fi
fi
