version: '3.7'

services:
    go:
        image: bhuisgen/alpine-go
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - ENV=local                             # environment name
