#!/usr/bin/with-contenv sh

if [ ! -z ${LOGSTASH_TEMPLATE} ]; then
    echo "==> Enabling logstash template '${LOGSTASH_TEMPLATE}'"

    cp "/etc/consul-template/templates/logstash/${LOGSTASH_TEMPLATE}.conf" /etc/consul-template/conf-services.d/10-logstash.conf
fi
