version: '3.5'

volumes:
    zabbix-java-gateway:

services:
    zabbix-java-gateway:
        depends_on:
            - consul                                        # consul agent
        image: bhuisgen/alpine-zabbix-java-gateway
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - zabbix-java-gateway:/var/lib/zabbix           # volume for data
        environment:
            - ENV=local                                     # environment name
            - CONSUL_AGENT=consul                           # consul agent hostname/IP
            #- CONSUL_PORT=8500                             # consul agent port
            #- CONSUL_KEYPREFIX=path/prefix/                # consul key prefix path
            - CONSUL_SERVICENAME=zabbix-java-gateway        # consul service name
            - CONSUL_SERVICETAGS=local                      # consul service tag
            - CONSUL_SERVICEPORT=10052                      # consul service port
            - CONSUL_CHECKTYPE=tcp                          # consul health check type
            - ZABBIX_STARTPOLLERS=5                         # number of zabbix worker threads
            - ZABBIX_TIMEOUT=3                              # network operations timeout
            - ZABBIX_JMX=0                                  # enable JMX monitoring
            #- ZABBIX_JMXAUTH=0                             # enable JMX authentication
            #- ZABBIX_JMXUSERNAME=zabbix                    # JMX username
            #- ZABBIX_JMXPASSWORD=zabbix                    # JMX password
            #- ZABBIX_JMXSSL=0                              # enable SSL protocol for JMX
            #- ZABBIX_JMXSSLKEYSTORE=/usr/share/zabbix/zabbix_java/conf/truststore.jks      # JMX SSL keystore file
            #- ZABBIX_JMXSSLKEYSTOREPASSWORD=mysecret       # JMX SSL keystore password
            #- ZABBIX_JMXSSLTRUSTSTORE=/usr/share/zabbix/zabbix_java/conf/truststore.jks    # JMX SSL truststore file
            #- ZABBIX_JMXSSLTRUSTSTOREPASSWORD=mysecret     # JMX SSL truststore password
