version: '3.7'

volumes:
    openldap:

services:
    openldap:
        image: bhuisgen/alpine-openldap
        ports:
            - "389:389"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - openldap:/var/lib/openldap                # volume for data
        environment:
            - ENV=local                                 # environment name
            #- OPENLDAP_TEMPLATE=generic                # configuration template

            #
            # template generic
            #

            #- OPENLDAP_OLCROOTDN=cn=admin,cn=config                        # OLC root DN
            #- OPENLDAP_OLCROOTPW={SSHA}p12w1DrMOFl6TwXVrRlfLOa6Qwsa0avD    # OLC root password
