version: '3.5'

volumes:
    openldap:

services:
    openldap:
        image: bhuisgen/alpine-openldap
        ports:
            - "389:389"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - openldap:/var/lib/openldap                # volume for data
        environment:
            - ENV=local                                 # environment name
            #- VAULT_ADDR=                              # vault address
            #- VAULT_TLS=1                              # enable TLS
            #- VAULT_TOKEN=                             # vault token
            #- VAULT_SECRET=local/openldap/             # secret path
            #- CONSUL_ADDR=                             # consul address
            #- CONSUL_TLS=1                             # enable TLS
            #- CONSUL_TLSCAFILE=                        # TLS CA certificate file
            #- CONSUL_TLSCERTFILE=                      # TLS client certificate file
            #- CONSUL_TLSKEYFILE=                       # TLS client certificate key file
            #- CONSUL_TOKEN=                            # consul token
            #- CONSUL_KEYPREFIX=local/openldap/         # consul key prefix path
            #- CONSUL_SERVICENAME=openldap              # consul service name
            #- CONSUL_SERVICETAGS=local                 # consul service tag
            #- CONSUL_SERVICEPORT=389                   # consul service port
            #- CONSUL_CHECKTYPE=tcp                     # consul health check type
            - OPENLDAP_TEMPLATE=generic                 # configuration template

            #
            # template generic
            #

            - OPENLDAP_OLCROOTDN=cn=admin,cn=config                     # OLC root DN
            - OPENLDAP_OLCROOTPW={SSHA}p12w1DrMOFl6TwXVrRlfLOa6Qwsa0avD # OLC root password
