version: '3.7'

services:
    jetty:
        image: bhuisgen/alpine-jetty
        ports:
            - "8080:8080"
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - ENV=local                             # environment name
            - JETTY_TEMPLATE=generic                # configuration template

            #
            # template generic
            #
