version: '3.5'

volumes:
    jetty:

services:
    jetty:
        depends_on:
            - consul                                # consul agent
        image: bhuisgen/alpine-jetty
        ports:
            - "8080:8080"
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - ENV=local                             # environment name
            - CONSUL_AGENT=consul                   # consul agent hostname/IP
            #- CONSUL_PORT=8500                     # consul agent port
            #- CONSUL_KEYPREFIX=path/prefix/        # consul key prefix path
            - CONSUL_SERVICENAME=jetty              # consul service name
            - CONSUL_SERVICETAGS=local              # consul service tag
            - CONSUL_SERVICEPORT=8080               # consul service port
            - CONSUL_CHECKTYPE=tcp                  # consul health check type
