#!/usr/bin/env bash

if [ ! -z "${CONTAINER_NAME}" ] && [ ! -z "${CONTAINER_IP}" ]; then
    rm -f /var/run/s6/container_environment/CONTAINER_NAME
    rm -f /var/run/s6/container_environment/CONTAINER_IP
fi
