#!/usr/bin/with-contenv sh

if [ ! -z "${POSTGRESQL_TEMPLATE}" ]; then
    echo "==> Enabling template ${POSTGRESQL_TEMPLATE}"

    cp "/etc/consul-template/templates/postgresql/${POSTGRESQL_TEMPLATE}"/*.hcl /etc/consul-template/conf.d/
fi
