#!/usr/bin/with-contenv sh

if [ -z ${MARIADB_CONFIG} ]; then
    echo "==> Configuring mariadb"

    mkdir -p /var/run/mysqld
    chown -R mysql:root /var/run/mysqld
    mysql_install_db --basedir=/usr --datadir=/var/lib/mysql --user=mysql

    /usr/bin/mysqld_safe --skip-networking > /dev/null 2>&1 &

    RET=1
    while [[ $RET -ne 0 ]]; do
        sleep 4
        mysql -u root -e "status" > /dev/null 2>&1
        RET=$?
    done

    if [ ! -z ${MARIADB_ROOTPASSWORD} ]; then
        echo "==> Setting root password"
        mysql -u root -e "UPDATE user SET password=PASSWORD('${MARIADB_ROOTPASSWORD}') WHERE User='root'; FLUSH PRIVILEGES;" mysql
    fi

    if [ ! -z ${MARIADB_DATABASE} ] && [ ! -z ${MARIADB_USERNAME} ] && [ ! -z ${MARIADB_PASSWORD} ] && [ ! -z ${MARIADB_HOSTMASK} ]; then
        echo "==> Creating database and user"
        mysql -u root -p"${MARIADB_ROOTPASSWORD}" \
            -e "CREATE DATABASE \`${MARIADB_DATABASE}\`;" \
            -e "CREATE USER '${MARIADB_USERNAME}'@'${MARIADB_HOSTMASK}' IDENTIFIED BY '${MARIADB_PASSWORD}';" \
            -e "GRANT ALL ON \`${MARIADB_DATABASE}\`.* TO '${MARIADB_USERNAME}'@'${MARIADB_HOSTMASK}';" \
            -e "FLUSH PRIVILEGES;" mysql
    fi

    if [ ! -z ${MARIADB_CONFIGSCRIPT} ]; then
        /bin/sh ${MARIADB_CONFIGSCRIPT} ${MARIADB_ROOTPASSWORD}
    fi

    mysqladmin -u root -p"${MARIADB_ROOTPASSWORD}" shutdown
    sleep 4

    export MARIADB_CONFIG=1
    printf "%s" "${MARIADB_CONFIG}" > /var/run/s6/container_environment/MARIADB_CONFIG
fi
