#!/usr/bin/with-contenv sh

echo "==> Initialize MariaDB"
mkdir -p /var/run/mysqld
chown -R mysql:root /var/run/mysqld
mysql_install_db --basedir=/usr --datadir=/var/lib/mysql --user=mysql

/usr/bin/mysqld_safe > /dev/null 2>&1 &

RET=1
while [[ $RET -ne 0 ]]; do
    sleep 4
    mysql -uroot -e "status" > /dev/null 2>&1
    RET=$?
done

mysql -u root -h localhost -e "CREATE DATABASE \`${MARIADB_DATABASE}\`"
mysql -u root -h localhost -e "GRANT ALL PRIVILEGES ON \`${MARIADB_DATABASE}\`.* TO '${MARIADB_USERNAME}'@'${MARIADB_HOSTNAME}' IDENTIFIED BY '${MARIADB_PASSWORD}'"

mysqladmin -u root -h localhost shutdown
