version: '3.5'

volumes:
    kapacitor:

services:
    kapacitor:
        depends_on:
            - consul                                # consul agent
        image: bhuisgen/alpine-kapacitor
        ports:
            - "9092:9092"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - kapacitor:/var/lib/kapacitor          # volume for data
        environment:
            - ENV=local                             # environment name
            - CONSUL_AGENT=consul                   # consul agent hostname/IP
            #- CONSUL_PORT=8500                     # consul agent port
            #- CONSUL_KEYPREFIX=path/prefix/        # consul key prefix path
            - CONSUL_SERVICENAME=kapacitor          # consul service name
            - CONSUL_SERVICETAGS=local              # consul service tag
            - CONSUL_SERVICEPORT=9092               # consul service port
            - CONSUL_CHECKTYPE=tcp                  # consul health check type
