version: '3.8'

volumes:
    kapacitor:

services:
    kapacitor:
        image: bhuisgen/alpine-kapacitor
        ports:
            - "9092:9092"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - kapacitor:/var/lib/kapacitor          # volume for data
        environment:
            - ENV=local                             # environment name
            - KAPACITOR_TEMPLATE=generic            # configuration template

            #
            # template generic
            #

            #- KAPACITOR_INFLUXDBNAME=influxdb              # influxdb server name
            #- KAPACITOR_INFLUXDBURLS=http://influxdb:8086  # influxdb server URL (comma separated list)
            #- KAPACITOR_INFLUXDBUSERNAME=                  # influxdb auth username
            #- KAPACITOR_INFLUXDBPASSWORD=                  # influxdb auth password
