#!/usr/bin/with-contenv sh

if [ ! -z "${JETTY_TEMPLATE}" ]; then
    echo "==> Enabling template ${JETTY_TEMPLATE}"

    cp "/etc/consul-template/templates/jetty/${JETTY_TEMPLATE}"/*.hcl /etc/consul-template/conf.d/
fi
