version: '3.8'

volumes:
    node-red:

services:
    node-red:
        image: bhuisgen/alpine-node-red
        privileged: true
        ports:
            - "1880:1880"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - node-red:/var/lib/node-red                    # volume for data
        environment:
            - ENV=local                                     # environment name
            #- NODERED_TEMPLATE=generic                     # configuration template

            #
            # template generic
            #

            #- NODERED_OPTIONS=                             # exec options
