version: '3.8'

volumes:
    certbot:

services:
    certbot:
        image: bhuisgen/alpine-certbot
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - certbot:/data
        environment:
            - ENV=local
