version: '3.2'

services:
    consul:
        image: bhuisgen/alpine-consul
        ports:
            - "8500:8500"
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - CONSUL_OPTIONS=-server -bootstrap-expect 1 -client 0.0.0.0 -ui    # minimal server options

    docker-registry:
        depends_on:
            - consul
        image: bhuisgen/alpine-docker-registry
        ports:
            - "5000:5000"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            #- /host/data:/var/lib/docker-registry  # volume for data
        environment:
            - CONSUL_AGENT=consul                   # consul agent hostname/IP
            #- CONSUL_PORT=8500                     # consul agent port
            #- CONSUL_KEYPREFIX=path/prefix/        # consul key prefix path
            - CONSUL_SERVICENAME=docker-registry    # consul service name
            - CONSUL_SERVICETAGS=dev                # consul service tag
            - CONSUL_SERVICEPORT=5000               # consul service port
            - CONSUL_CHECKTYPE=tcp                  # consul health check type
