version: '3.7'

volumes:
    docker-registry:

services:
    docker-registry:
        image: bhuisgen/alpine-docker-registry
        ports:
            - "5000:5000"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - docker-registry:/var/lib/docker-registry  # volume for data
        environment:
            - ENV=local                                 # environment name
            #- REGISTRY_TEMPLATE=generic                # configuration template

            #
            # template generic
            #
