version: '3.5'

volumes:
    docker-registry:

services:
    docker-registry:
        depends_on:
            - consul                                    # consul agent
        image: bhuisgen/alpine-docker-registry
        ports:
            - "5000:5000"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - docker-registry:/var/lib/docker-registry  # volume for data
        environment:
            - ENV=local                                 # environment name
            - CONSUL_AGENT=consul                       # consul agent hostname/IP
            #- CONSUL_PORT=8500                         # consul agent port
            #- CONSUL_KEYPREFIX=path/prefix/            # consul key prefix path
            - CONSUL_SERVICENAME=docker-registry        # consul service name
            - CONSUL_SERVICETAGS=local                  # consul service tag
            - CONSUL_SERVICEPORT=5000                   # consul service port
            - CONSUL_CHECKTYPE=tcp                      # consul health check type
