#!/usr/bin/with-contenv sh

if [ ! -z "${REDIS_TEMPLATE}" ]; then
    echo "==> Enabling template ${REDIS_TEMPLATE}"

    cp "/etc/consul-template/templates/redis/${REDIS_TEMPLATE}"/*.hcl /etc/consul-template/conf.d/
fi
