#!/usr/bin/with-contenv sh

if [ ! -z "${OPENSSH_TEMPLATE}" ]; then
    echo "==> Enabling template ${OPENSSH_TEMPLATE}"

    cp "/etc/consul-template/templates/openssh/${OPENSSH_TEMPLATE}"/*.hcl /etc/consul-template/conf.d/
fi
