#!/usr/bin/with-contenv sh

if [ ! -z "${KIBANA_TEMPLATE}" ]; then
    echo "==> Enabling template ${KIBANA_TEMPLATE}"

    cp "/etc/consul-template/templates/kibana/${KIBANA_TEMPLATE}"/*.hcl /etc/consul-template/conf.d/
fi
