version: '3.8'

volumes:
    drone:

services:
    drone-server:
        image: bhuisgen/alpine-drone
        ports:
            - "8000:8000"
            - "9000:9000"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - drone:/var/lib/drone                          # volume for data
        environment:
            - ENV=local                                     # environment name
            #- DRONE_TEMPLATE=generic                       # configuration template

            #
            # template generic
            #

            - DRONE_HOST=0.0.0.0
            - DRONE_OPEN=true
            - DRONE_SECRET=my$ecret
            - DRONE_DATABASE_DRIVER=sqlite3
            - DRONE_DATABASE_DATASOURCE=/var/lib/drone/drone.sqlite
            - DRONE_GOGS=true
            - DRONE_GOGS_URL=http://gogs.my.domain:3000

    drone-agent:
        depends_on:
            - consul                                        # consul agent
        image: bhuisgen/alpine-drone
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - ENV=local                                     # environment name
            #- DRONE_TEMPLATE=generic                       # configuration template

            #
            # template generic
            #

            - DRONE_SERVER=drone-server:9000
            - DRONE_SECRET=my$ecret
