version: '3.7'

volumes:
    opendkim:

services:
    opendkim:
        image: bhuisgen/alpine-opendkim
        ports:
            - "8891:8891"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /dev/log:/dev/log
            - opendkim:/var/lib/opendkim            # volume for data
        environment:
            - ENV=local                             # environment name
            #- OPENDKIM_TEMPLATE=generic            # configuration template

            #
            # template generic
            #

            #- OPENDKIM_KEYTABLE=                   # opendkim key table file of signing keys
            #- OPENDKIM_SIGNINGTABLE=               # opendkim table file for selecting signatures
            #- OPENDKIM_EXTERNALIGNORELIST=         # opendkim ignore list file
            #- OPENDKIM_INTERNALHOSTS=              # opendkim internal hosts file
