version: '3.5'

volumes:
    opendkim:

services:
    opendkim:
        depends_on:
            - consul                                # consul agent
        image: bhuisgen/alpine-opendkim
        ports:
            - "8891:8891"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /dev/log:/dev/log
            - opendkim:/var/lib/opendkim            # volume for data
        environment:
            - ENV=local                             # environment name
            - CONSUL_AGENT=consul                   # consul agent hostname/IP
            #- CONSUL_PORT=8500                     # consul agent port
            #- CONSUL_KEYPREFIX=path/prefix/        # consul key prefix path
            - CONSUL_SERVICENAME=opendkim           # consul service name
            - CONSUL_SERVICETAGS=local              # consul service tag
            - CONSUL_SERVICEPORT=8891               # consul service port
            - CONSUL_CHECKTYPE=tcp                  # consul health check type
            - OPENDKIM_DEFAULT=default              # configuration template

            #
            # template opendkim
            #

            #- OPENDKIM_KEYTABLE=                   # opendkim key table file of signing keys
            #- OPENDKIM_SIGNINGTABLE=               # opendkim table file for selecting signatures
            #- OPENDKIM_EXTERNALIGNORELIST=         # opendkim ignore list file
            #- OPENDKIM_INTERNALHOSTS=              # opendkim internal hosts file
