version: '3.8'

services:
    hostapd:
        image: bhuisgen/alpine-hostapd
        cap_add:
            - NET_ADMIN
        network_mode: host
        devices:
            - /dev/rfkill
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - ENV=local                             # environment name
            #- HOSTAPD_TEMPLATE=generic             # configuration template

            #
            # template generic
            #

            #- HOSTAPD_INTERFACE=wlx74da386015cd    # AP interface
            #- HOSTAPD_SSID=${USERNAME}             # AP network SSID
            #- HOSTAPD_COUNTRYCODE=FR               # AP country code
            #- HOSTAPD_WPAPASSPHRASE=1234567890     # AP WPA passphrase
            #- HOSTAPD_WPAKEYMGMT=WPA-PSK           # AP WPA key management
            #- HOSTAPD_WPAPAIRWISE=TKIP             # AP WPA pairwise
            #- HOSTAPD_RSNPAIRWISE=CCMP             # AP RNS pairwise
