#!/usr/bin/with-contenv sh

if [ -z ${STRONGSWAN_CONFIG} ]; then
    echo "==> Configuring strongswan"

    sysctl -w net.ipv4.ip_forward=1
    sysctl -w net.ipv4.conf.all.accept_redirects=0
    sysctl -w net.ipv4.conf.all.send_redirects=0

    iptables -A INPUT -p udp --dport 500 --j ACCEPT
    iptables -A INPUT -p udp --dport 4500 --j ACCEPT
    iptables -A INPUT -p esp -j ACCEPT
    iptables -t nat -A POSTROUTING -s $STRONGSWAN_LEFTSUBNET -o $STRONGSWAN_INTERFACE -m policy --dir out --pol ipsec -j ACCEPT
    iptables -t nat -A POSTROUTING -s $STRONGSWAN_LEFTSUBNET -o $STRONGSWAN_INTERFACE -j MASQUERADE

    cat > /etc/ipsec.conf <<EOF
# ipsec.conf

config setup
    charondebug="ike 2, knl 2, cfg 2, mgr 3, chd 2, net 2"

conn %default
    ikelifetime=60m
    keylife=20m
    rekeymargin=3m
    keyingtries=1
    keyexchange=ikev2
    mobike=no

conn ipsec-ikev2
    left=$STRONGSWAN_LEFT
    leftsubnet=$STRONGSWAN_LEFTSUBNET
    leftcert=$STRONGSWAN_LEFTCERT
    leftid=$STRONGSWAN_LEFTID
    leftfirewall=yes
    right=$STRONGSWAN_RIGHT
    rightsubnet=$STRONGSWAN_RIGHTSUBNET
    rightid=$STRONGSWAN_RIGHTID
    dpdaction=restart
    dpddelay=30
    auto=$STRONGSWAN_AUTO

# end
EOF

    cat > /etc/ipsec.secrets <<EOF
# ipsec.secrets

: RSA "$STRONGSWAN_LEFTKEY"

# end
EOF
    chmod 640 ipsec.conf ipsec.secrets

    export STRONGSWAN_CONFIG=1
    printf "%s" "${STRONGSWAN_CONFIG}" > /var/run/s6/container_environment/STRONGSWAN_CONFIG
fi
