#!/usr/bin/with-contenv sh

echo "==> Configuring iptables"

sysctl -w net.ipv4.ip_forward=1
sysctl -w net.ipv4.conf.all.accept_redirects=0
sysctl -w net.ipv4.conf.all.send_redirects=0

iptables -A INPUT -i "${STRONGSWAN_INTERFACE}" -p udp --dport 500 --j ACCEPT
iptables -A INPUT -i "${STRONGSWAN_INTERFACE}" -p udp --dport 4500 --j ACCEPT
iptables -A OUTPUT -o "${STRONGSWAN_INTERFACE}" -p udp --dport 500 --j ACCEPT
iptables -A OUTPUT -o "${STRONGSWAN_INTERFACE}" -p udp --dport 4500 --j ACCEPT
iptables -A FORWARD -i "${STRONGSWAN_INTERFACE}" -o "${STRONGSWAN_INTERFACE}" -s "${STRONGSWAN_LEFTSUBNET}" -m policy --dir in --pol ipsec --proto esp -j ACCEPT
iptables -A FORWARD -i "${STRONGSWAN_INTERFACE}" -o "${STRONGSWAN_INTERFACE}" -d "${STRONGSWAN_LEFTSUBNET}" -m policy --dir out --pol ipsec --proto esp -j ACCEPT

echo "==> Configuring strongswan"

cat > /etc/ipsec.conf <<EOF
# ipsec.conf

config setup
    charondebug="ike 2, knl 2, cfg 2, mgr 3, chd 2, net 2"

conn %default
    ikelifetime=60m
    keylife=20m
    rekeymargin=3m
    keyingtries=1
    keyexchange=ikev2
    mobike=no

conn ipsec-ikev2
    left=$STRONGSWAN_LEFT
    leftsubnet=$STRONGSWAN_LEFTSUBNET
    leftcert=$STRONGSWAN_LEFTCERT
    leftid=$STRONGSWAN_LEFTID
    leftfirewall=yes
    right=$STRONGSWAN_RIGHT
    rightsubnet=$STRONGSWAN_RIGHTSUBNET
    rightid=$STRONGSWAN_RIGHTID
    dpdaction=restart
    dpddelay=30
    auto=$STRONGSWAN_AUTO

# end
EOF

cat > /etc/ipsec.secrets <<EOF
# ipsec.secrets

: RSA "$STRONGSWAN_LEFTKEY"

# end
EOF
chmod 640 ipsec.conf ipsec.secrets

