version: '3.8'

volumes:
    telegraf:

services:
    telegraf:
        image: bhuisgen/alpine-telegraf
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - telegraf:/var/lib/telegraf            # volume for data
        environment:
            - ENV=local                             # environment name
            - TELEGRAF_TEMPLATE=generic             # configuration template

            #
            # template generic
            #

            #- TELEGRAF_INFLUXDBURLS=http://influxdb:8086   # influxdb server URL (comma separated list)
            #- TELEGRAF_INFLUXDBDATABASE=telegraf           # influxdb database
            #- TELEGRAF_INFLUXDBUSERNAME=                   # influxdb auth username
            #- TELEGRAF_INFLUXDBPASSWORD=                   # influxdb auth password
