version: 0.1
log:
    fields:
        service: docker-registry
storage:
    cache:
        blobdescriptor: inmemory
    filesystem:
        rootdirectory: /var/lib/docker-registry
http:
    addr: :5000
    headers:
        X-Content-Type-Options: [nosniff]
