#!/usr/bin/with-contenv sh

if [ ! -f /var/lib/nomad/.config ]; then
    echo "==> Configuring nomad"

    if [ -S /var/run/docker.sock ]; then
        GID=$(stat -c "%g" /var/run/docker.sock)
        GROUP=$(getent group ${GID}|cut -d ':' -f 1)

        if [ ! -z "${GROUP}" ]; then
            adduser nomad "${GROUP}"
        else
            addgroup -g "${GID}" -S docker
            adduser nomad docker
        fi
    fi

    touch /var/lib/nomad/.config
fi
