version: '3.8'

volumes:
    rundeck:

services:
    rundeck:
        image: bhuisgen/alpine-rundeck
        ports:
            - "4440:4440"
            - "4443:4443"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - rundeck:/home/rundeck                     # volume for data
        environment:
            - ENV=local                                 # environment name
            #- RUNDECK_TEMPLATE=generic                 # configuration template

            #
            # template generic
            #

            #- RUNDECK_SERVERURL=http://0.0.0.0:4440    # external server URL
            #- RUNDECK_DATASOURCEDRIVERCLASSNAME=       # datasource driver class name
            #- RUNDECK_DATASOURCEURL=                   # datasource URL
            #- RUNDECK_DATASOURCEUSERNAME=              # datasource username
            #- RUNDECK_DATASOURCEPASSWORD=              # datasource password
