version: '3.5'

volumes:
    rundeck:

services:
    rundeck:
        depends_on:
            - consul                                    # consul agent
        image: bhuisgen/alpine-rundeck
        ports:
            - "4440:4440"
            - "4443:4443"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - rundeck:/home/rundeck                     # volume for data
        environment:
            - ENV=local                                 # environment name
            - CONSUL_AGENT=consul                       # consul agent hostname/IP
            #- CONSUL_PORT=8500                         # consul agent port
            #- CONSUL_KEYPREFIX=path/prefix/            # consul key prefix path
            - RUNDECK_SERVERURL=http://0.0.0.0:4440     # rundeck external server URL
