#!/usr/bin/env bash

trap 'exit 2' INT TERM

echo "==> Checking haproxy configuration"

haproxy -c -q -f /etc/haproxy/haproxy.cfg || exit 1

stats_socket=$(grep "stats socket" /etc/haproxy/haproxy.cfg|awk '{ print $3; }')
if [ ! -e "${stats_socket}" ]; then
   exit 1
fi

echo "==> Retrieving haproxy frontends"

stat=$(echo "show stat"|socat "${stats_socket}" stdio|awk 'NR>1 && /,FRONTEND/ && !/stats/')
frontends=$(echo "${stat}"|awk -F ',' '{ print $1; }')

if [ ! -z "$1" ] && [ "$1" == "--enable" ]; then
    echo "==> Enabling haproxy maintenance mode"

    for frontend in ${frontends}; do
        echo "disable frontend ${frontend}"|socat "${stats_socket}" stdio > /dev/null
    done
elif [ ! -z "$1" ] && [ "$1" == "--disable" ]; then
    echo "==> Disabling haproxy maintenance mode"

    for frontend in ${frontends}; do
        echo "enable frontend ${frontend}"|socat "${stats_socket}" stdio > /dev/null
    done
else
    echo "==> Checking haproxy status"
    echo "${stat}"
fi
