version: '3.5'

volumes:
    backups:

services:
    backup-tar:
        image: bhuisgen/alpine-backup-mongodb
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - backups:/var/backups              # volume for backups
            - data:/data                        # volume for data
        environment:
            - ENV=dev                           # environment name
            #- BACKUP_PATH=/var/backups         # backup storage path
            - BACKUP_TAR_DIR=/data              # data directory to backup
