version: '3.7'

volumes:
    data:

services:
    backup-tar:
        image: bhuisgen/alpine-backup-mongodb
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /srv/backups:/var/backups             # volume for storage
            - data:/data                            # volume to backup
        environment:
            - ENV=local                             # environment name
            #- BACKUP_PATH=/var/backups             # backup storage path
            - BACKUP_TAR_DIR=/data                  # data directory to backup (required)
