version: '3.2'

services:
    consul:
        image: bhuisgen/alpine-consul
        ports:
            - "8500:8500"
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - CONSUL_OPTIONS=-server -bootstrap-expect 1 -client 0.0.0.0 -ui    # minimal server options

    vault:
        image: bhuisgen/alpine-nomad
        cap-add:
            - IPC_LOCK
        ports:
            - "8200:8200"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            #- /host/data:/var/lib/vault                                        # volume for data
        environment:
            - CONSUL_AGENT=consul                                               # consul agent hostname/IP
            #- CONSUL_PORT=8500                                                 # consul agent port
            #- CONSUL_KEYPREFIX=path/pref                                       # consul key prefix path
            - CONSUL_SERVICENAME=vault                                          # consul service name
            - CONSUL_SERVICETAGS=dev                                            # consul service tag
            - CONSUL_SERVICEPORT=8200                                           # consul service port
            - CONSUL_CHECKTYPE=tcp                                              # consul health check type
