version: '3.5'

volumes:
    vault:

services:
    vault:
        depends_on:
            - consul                                        # consul agent
        image: bhuisgen/alpine-vault
        cap_add:
            - IPC_LOCK
        ports:
            - "8200:8200"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - vault:/var/lib/vault                          # volume for data
        environment:
            - ENV=local                                     # environment name
            - CONSUL_AGENT=consul                           # consul agent hostname/IP
            #- CONSUL_PORT=8500                             # consul agent port
            #- CONSUL_KEYPREFIX=path/pref                   # consul key prefix path
            - CONSUL_SERVICENAME=vault                      # consul service name
            - CONSUL_SERVICETAGS=local                      # consul service tag
            - CONSUL_SERVICEPORT=8200                       # consul service port
            - CONSUL_CHECKTYPE=tcp                          # consul health check type
            - VAULT_TEMPLATE=file                           # configuration template

            #
            # template consul
            #

            #- VAULT_CLUSTERNAME=                           # vault cluster name
            - VAULT_LISTENERTLSDISABLE=1                    # disable TLS for listener
            #- VAULT_LISTENERTLSCERTFILE=                   # TLS certificate file
            #- VAULT_LISTENERTLSKEYFILE=                    # TLS key file
            #- VAULT_LISTENERTLSMINVERSION=                 # TLS minimum version allowed
            #- VAULT_LISTENERTLSCIPHERSUITES=               # TLS supported cipher suites
            #- VAULT_LISTENERTLSPREFERSERVERCIPHERSUITES=   # prefer server's cipher suites
            #- VAULT_LISTENERTLSREQUIREANDVERIFYCLIENTCERT= # enable TLS client authentication
            #- VAULT_LISTENERTLSCLIENTCAFILE=               # TLS client CA file
            #- VAULT_STORAGEADDRESS=                        # consul address
            #- VAULT_STORAGEPATH=                           # consul path

            #
            # template file
            #

            #- VAULT_CLUSTERNAME=                           # vault cluster name
            - VAULT_LISTENERTLSDISABLE=1                    # disable TLS for listener
            #- VAULT_LISTENERTLSCERTFILE=                   # TLS certificate file
            #- VAULT_LISTENERTLSKEYFILE=                    # TLS key file
            #- VAULT_LISTENERTLSMINVERSION=                 # TLS minimum version allowed
            #- VAULT_LISTENERTLSCIPHERSUITES=               # TLS supported cipher suites
            #- VAULT_LISTENERTLSPREFERSERVERCIPHERSUITES=   # prefer server's cipher suites
            #- VAULT_LISTENERTLSREQUIREANDVERIFYCLIENTCERT= # enable TLS client authentication
            #- VAULT_LISTENERTLSCLIENTCAFILE=               # TLS client CA file

            #
            # template mysql
            #

            #- VAULT_CLUSTERNAME=                           # vault cluster name
            - VAULT_LISTENERTLSDISABLE=1                    # disable TLS for listener
            #- VAULT_LISTENERTLSCERTFILE=                   # TLS certificate file
            #- VAULT_LISTENERTLSKEYFILE=                    # TLS key file
            #- VAULT_LISTENERTLSMINVERSION=                 # TLS minimum version allowed
            #- VAULT_LISTENERTLSCIPHERSUITES=               # TLS supported cipher suites
            #- VAULT_LISTENERTLSPREFERSERVERCIPHERSUITES=   # prefer server's cipher suites
            #- VAULT_LISTENERTLSREQUIREANDVERIFYCLIENTCERT= # enable TLS client authentication
            #- VAULT_LISTENERTLSCLIENTCAFILE=               # TLS client CA file
            #- VAULT_STORAGEUSERNAME=                       # database username
            #- VAULT_STORAGEPASSWORD=                       # database password
            #- VAULT_STORAGEDATABASE=                       # database name

            #
            # template postgresql
            #

            #- VAULT_CLUSTERNAME=                           # vault cluster name
            - VAULT_LISTENERTLSDISABLE=1                    # disable TLS for listener
            #- VAULT_LISTENERTLSCERTFILE=                   # TLS certificate file
            #- VAULT_LISTENERTLSKEYFILE=                    # TLS key file
            #- VAULT_LISTENERTLSMINVERSION=                 # TLS minimum version allowed
            #- VAULT_LISTENERTLSCIPHERSUITES=               # TLS supported cipher suites
            #- VAULT_LISTENERTLSPREFERSERVERCIPHERSUITES=   # prefer server's cipher suites
            #- VAULT_LISTENERTLSREQUIREANDVERIFYCLIENTCERT= # enable TLS client authentication
            #- VAULT_LISTENERTLSCLIENTCAFILE=               # TLS client CA file
            #- VAULT_STORAGECONNECTIONURL=                  # database connection URL

            #
            # template s3
            #

            #- VAULT_CLUSTERNAME=                           # vault cluster name
            - VAULT_LISTENERTLSDISABLE=1                    # disable TLS for listener
            #- VAULT_LISTENERTLSCERTFILE=                   # TLS certificate file
            #- VAULT_LISTENERTLSKEYFILE=                    # TLS key file
            #- VAULT_LISTENERTLSMINVERSION=                 # TLS minimum version allowed
            #- VAULT_LISTENERTLSCIPHERSUITES=               # TLS supported cipher suites
            #- VAULT_LISTENERTLSPREFERSERVERCIPHERSUITES=   # prefer server's cipher suites
            #- VAULT_LISTENERTLSREQUIREANDVERIFYCLIENTCERT= # enable TLS client authentication
            #- VAULT_LISTENERTLSCLIENTCAFILE=               # TLS client CA file
            #- VAULT_STORAGEACCESSKEY=                      # S3 accesss key
            #- VAULT_STORAGESECRETKEY=                      # S3 secret key
            #- VAULT_STORAGEBUCKET=                         # S3 bucket
