version: '3.2'

services:
    consul:
        image: bhuisgen/alpine-consul
        ports:
            - "8500:8500"
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - CONSUL_OPTIONS=-server -bootstrap-expect 1 -client 0.0.0.0 -ui    # minimal server options

    vault:
        depends_on:
            - consul
        image: bhuisgen/alpine-vault
        cap_add:
            - IPC_LOCK
        ports:
            - "8200:8200"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            #- /host/data:/var/lib/vault                                        # volume for data
        environment:
            - CONSUL_AGENT=consul                                               # consul agent hostname/IP
            #- CONSUL_PORT=8500                                                 # consul agent port
            #- CONSUL_KEYPREFIX=path/pref                                       # consul key prefix path
            - CONSUL_SERVICENAME=vault                                          # consul service name
            - CONSUL_SERVICETAGS=dev                                            # consul service tag
            - CONSUL_SERVICEPORT=8200                                           # consul service port
            - CONSUL_CHECKTYPE=tcp                                              # consul health check type
            #- VAULT_CLUSTERNAME=                                               # vault cluster name
            - VAULT_LISTENERTLSDISABLE=1                                        # disable TLS for listener
            #- VAULT_LISTENERTLSCERTFILE=                                       # TLS certificate file
            #- VAULT_LISTENERTLSKEYFILE=                                        # TLS key file
            #- VAULT_LISTENERTLSMINVERSION=                                     # TLS minimum version allowed
            #- VAULT_LISTENERTLSCIPHERSUITES=                                   # TLS supported cipher suites
            #- VAULT_LISTENERTLSPREFERSERVERCIPHERSUITES=                       # prefer server's cipher suites
            #- VAULT_LISTENERTLSREQUIREANDVERIFYCLIENTCERT=                     # enable TLS client authentication
            #- VAULT_LISTENERTLSCLIENTCAFILE=                                   # TLS client CA file
            - VAULT_TEMPLATE=consul                                             # configuration template
            #
            # template consul
            #
            - VAULT_TEMPLATE_CONSUL_STORAGEADDRESS=consul                       # consul address
            #- VAULT_TEMPLATE_CONSUL_STORAGEPATH=                               # consul path
            #
            # template file
            #
            #- VAULT_TEMPLATE_FILE_STORAGEPATH=                                 # filesystem path
            #
            # template mysql
            #
            #- VAULT_TEMPLATE_MYSQL_STORAGEUSERNAME=                            # database username
            #- VAULT_TEMPLATE_MYSQL_STORAGEPASSWORD=                            # database password
            #- VAULT_TEMPLATE_MYSQL_STORAGEDATABASE=                            # database name
            #
            # template postgresql
            #
            #- VAULT_TEMPLATE_POSTGRESQL_STORAGECONNECTIONURL=                  # database connection URL
            #
            # template s3
            #
            #- VAULT_TEMPLATE_S3_STORAGEACCESSKEY=                              # S3 accesss key
            #- VAULT_TEMPLATE_S3_STORAGESECRETKEY=                              # S3 secret key
            #- VAULT_TEMPLATE_S3_STORAGEBUCKET=                                 # S3 bucket
