#!/usr/bin/with-contenv sh

if [ ! -z "${HAPROXY_TEMPLATE}" ]; then
    HAPROXY_TEMPLATE=default
fi

echo "==> Enabling template ${HAPROXY_TEMPLATE}"

cp "/etc/consul-template/templates/haproxy/${HAPROXY_TEMPLATE}"/*.hcl /etc/consul-template/conf.d/
