#!/usr/bin/with-contenv sh

if [ ! -z ${HAPROXY_TEMPLATE} ]; then
    echo "==> Enabling haproxy template '${HAPROXY_TEMPLATE}'"

    cp "/etc/consul-template/templates/haproxy/${HAPROXY_TEMPLATE}.conf" /etc/consul-template/conf-services.d/10-haproxy.conf
fi
