version: '3.8'

services:
    syncthing:
        image: bhuisgen/alpine-syncthing
        ports:
            - "22000:22000"
            - "21027:21027/udp"
            - "8384:8384"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - $HOME/.syncthing:/var/lib/syncthing           # volume for configuration
            - $HOME:/data                                   # volume for storage
        environment:
            - ENV=local                                     # environment name
            - SYNCTHING_TEMPLATE=generic                    # configuration template

            #
            # template generic
            #

            #- SYNCTHING_UID=1000                           # userid for execution
            #- SYNCTHING_GID=1000                           # groupid for execution
