version: '3.5'

services:
    syncthing:
        depends_on:
            - consul                                        # consul agent
        image: bhuisgen/alpine-syncthing
        ports:
            - "22000:22000"
            - "21027:21027/udp"
            - "8384:8384"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - $HOME/.syncthing:/var/lib/syncthing           # volume for configuration
            - $HOME:/data                                   # volume for storage
        environment:
            - ENV=local                                     # environment name
            - CONSUL_AGENT=consul                           # consul agent hostname/IP
            #- CONSUL_PORT=8500                             # consul agent port
            #- CONSUL_KEYPREFIX=path/prefix/                # consul key prefix path
            - CONSUL_SERVICENAME=syncthing                  # consul service name
            - CONSUL_SERVICETAGS=local                      # consul service tag
            - CONSUL_SERVICEPORT=8443                       # consul service port
            - CONSUL_CHECKTYPE=tcp                          # consul health check type
            - SYNCTHING_TEMPLATE=static                     # configuration template

            #
            # template static
            #

            #- SYNCTHING_UID=1000                           # userid for execution
            #- SYNCTHING_GID=1000                           # groupid for execution
