#!/usr/bin/with-contenv sh

if [ ! -f /var/lib/elasticsearch/config ]; then
    echo "==> Configuring elasticsearch from environment"

    if [ -z "${ELASTICSEARCH_HEAPSIZE}" ]; then
        ELASTICSEARCH_HEAPSIZE=256M
        printf "%s" "${ELASTICSEARCH_HEAPSIZE}" > /var/run/s6/container_environment/ELASTICSEARCH_HEAPSIZE
    fi

    touch /var/lib/elasticsearch/config
fi
