version: '3.5'

volumes:
    roundcubemail:

services:
    roundcubemail:
        image: bhuisgen/alpine-roundcubemail
        entrypoint: /bin/sh
        volumes:
            - roundcubemail:/var/www
