version: '3.8'

volumes:
    roundcubemail:

services:
    roundcubemail:
        image: bhuisgen/alpine-roundcubemail
        entrypoint: /bin/sh
        volumes:
            - roundcubemail:/var/www
