version: '3.7'

volumes:
    chronograf:

services:
    chronograf:
        image: bhuisgen/alpine-chronograf
        ports:
            - "8888:8888"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - chronograf:/var/lib/chronograf        # volume for data
        environment:
            - ENV=local                             # environment name
            #- CHRONOGRAF_OPTIONS=                  # chronograf options
