version: '3.8'

volumes:
    data:

services:
    backup-rsync:
        image: bhuisgen/alpine-backup-rsync
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /srv/backups:/var/backups             # storage path
            - data:/data                            # data volume
        environment:
            - ENV=local                             # environment name
            #- BACKUP_PATH=/var/backups             # backup path
            #- BACKUP_DATA=/data                    # data directory to backup
            #- BACKUP_ROTATE=1                      # enable backup files rotation
            #- BACKUP_ROTATE_DAYS=3                 # number of backup to keep in days
