version: '3.7'

volumes:
    zabbix-monitor:

services:
    zabbix-monitor:
        image: bhuisgen/alpine-zabbix-monitor
        entrypoint: /bin/sh
        volumes:
            - zabbix-monitor:/var/www
