#!/usr/bin/with-contenv sh

if [ ! -f /var/lib/consul/.config ]; then
    echo "==> Configuring consul"

    consul-template -config /etc/consul-template/conf-env.d -once
    if [ $? -ne 0 ]; then
        echo "Failed to configure, aborting" >&2
        exit 1
    fi

    touch /var/lib/consul/.config
fi
