#!/usr/bin/with-contenv sh

echo "==> Generating consul configuration"

if ! consul-template -config /etc/consul-template/conf.d/ -once; then
    echo "Failed to generate consul configuration, aborting" >&2
    exit 1
fi
