#!/usr/bin/with-contenv sh

if [ ! -z "${ZABBIX_TEMPLATE}" ] && [ -z "${CONSUL_ADDR}" ]; then
    cp "/etc/container.d/templates/zabbix-java-gateway/${ZABBIX_TEMPLATE}"/*.hcl /etc/container.d/conf-init.d/
elif [ ! -z "${ZABBIX_TEMPLATE}" ] && [ ! -z "${CONSUL_ADDR}" ]; then
    cp "/etc/container.d/templates/zabbix-java-gateway/${ZABBIX_TEMPLATE}"/*.hcl /etc/container.d/conf-services.d/
fi
