#!/usr/bin/with-contenv sh

if [ ! -z "${INFLUXDB_TEMPLATE}" ]; then
    echo "==> Enabling template ${INFLUXDB_TEMPLATE}"

    cp "/etc/consul-template/templates/influxdb/${INFLUXDB_TEMPLATE}"/*.hcl /etc/consul-template/conf.d/
fi
