version: '3.7'

services:
    backup:
        image: bhuisgen/alpine-backup
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /srv/backups:/var/backups             # volume for storage
        environment:
            - ENV=local                             # environment name
