version: '3.5'

services:
    backup:
        image: bhuisgen/alpine-backup
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /srv/backups:/var/backups         # volume for storage
        environment:
            - ENV=dev                           # environment name
            #- BACKUP_PATH=/var/backups         # backup storage path
