#!/usr/bin/with-contenv sh

if [ -z ${CONSUL_AGENT} ]; then
    exit 0
fi

options=""
url="http://${CONSUL_AGENT}:${CONSUL_PORT}"
params=""

if [ ! -z ${CONSUL_TLS} ] && [ ${CONSUL_TLS} -eq 1 ]; then
    options="${options} --insecure --cacert /etc/consul.d/ssl/ca.pem --cert /etc/consul.d/ssl/client.pem --key /etc/consul.d/ssl/client-priv-key.pem"
    url="https://${CONSUL_AGENT}:${CONSUL_PORT}"
fi

if [ ! -z ${CONSUL_TOKEN} ]; then
    params="?token=${CONSUL_TOKEN}"
fi

status=0

if [ -d /etc/cont-consul/services.d/ ]; then
    for file in /etc/cont-consul/services.d/*.json; do
        [ -f "$file" ] || continue

        serviceid=$(jq -r '.ID' "$file") && curl -sSL ${options} -X GET "${url}/v1/agent/service/deregister/${serviceid}${params}" || status=1
    done
fi

if [ -d /etc/cont-consul/checks.d/ ]; then
    for file in /etc/cont-consul/checks.d/*.json; do
        [ -f "$file" ] || continue

        checkid=$(jq -r '.ID' "$file") && curl -sSL ${options} -X GET "${url}/v1/agent/check/deregister/${checkid}${params}" || status=1
    done
fi

exit $status
