version: '3.5'

services:
    unbound:
        depends_on:
            - consul                                # consul agent
        image: bhuisgen/alpine-unbound
        cap_add:
            - NET_ADMIN
        network_mode: host
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - ENV=local                             # environment name
            - CONSUL_AGENT=169.254.1.1              # consul agent hostname/IP
            #- CONSUL_PORT=8500                     # consul agent port
            #- CONSUL_KEYPREFIX=path/prefix/        # consul key prefix path
            - CONSUL_SERVICENAME=unbound            # consul service name
            - CONSUL_SERVICETAGS=local              # consul service tag
            - CONSUL_SERVICEPORT=53                 # consul service port
            - CONSUL_CHECKTYPE=tcp                  # consul health check type
            - UNBOUND_TEMPLATE=static               # configuration template

            #
            # template static
            #

            - UNBOUND_FORWARDADDR=8.8.8.8           # IP address to forward DNS requests
