version: '3.7'

services:
    unbound:
        image: bhuisgen/alpine-unbound
        cap_add:
            - NET_ADMIN
        network_mode: host
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - ENV=local                             # environment name
            #- UNBOUND_TEMPLATE=generic             # configuration template

            #
            # template generic
            #

            #- UNBOUND_FORWARDADDR=8.8.8.8          # IP address to forward DNS requests
