#!/usr/bin/with-contenv sh

CONTAINER_HOST=$(cat /etc/hostname)
if [ -z ${CONTAINER_HOST} ]; then
    exit 1
fi

if [ -z ${CONTAINER_IP_RESOLVER} ]; then
    CONTAINER_IP_RESOLVER=route
fi

case ${CONTAINER_IP_RESOLVER} in
    route)
        CONTAINER_IP=$(ip route get 1|awk '{ print $NF; exit; }')
        ;;

    interface)
        if [ -z ${CONTAINER_IP_RESOLVER_INTERFACENAME} ]; then
            CONTAINER_IP_RESOLVER_INTERFACENAME=eth0
        fi

        if [ -z ${CONTAINER_IP_RESOLVER_INTERFACETYPE} ]; then
            CONTAINER_IP_RESOLVER_INTERFACETYPE=inet
        fi

        CONTAINER_IP=$(ip -o addr show ${CONTAINER_IP_RESOLVER_INTERFACENAME}|grep "${CONTAINER_IP_RESOLVER_INTERFACETYPE} "|awk '{ print $4; }'|sed -e 's/\/.*$//')
        ;;
esac

if [ -z ${CONTAINER_IP} ]; then
    exit 2
fi

export CONTAINER_HOST
export CONTAINER_IP

printf "%s" "${CONTAINER_HOST}" > /var/run/s6/container_environment/CONTAINER_HOST
printf "%s" "${CONTAINER_IP}" > /var/run/s6/container_environment/CONTAINER_IP
