version: '3.2'

services:
    consul:
        image: bhuisgen/alpine-consul
        ports:
            - "8500:8500"
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - CONSUL_OPTIONS=-server -bootstrap-expect 1 -client 0.0.0.0 -ui    # minimal server options

    php:
        depends_on:
            - consul
        image: bhuisgen/alpine-php
        ports:
            - "9000:9000"
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - CONSUL_AGENT=consul                   # consul agent hostname/IP
            #- CONSUL_PORT=8500                     # consul agent port
            #- CONSUL_KEYPREFIX=path/prefix/        # consul key prefix path
            - CONSUL_SERVICENAME=php                # consul service name
            - CONSUL_SERVICETAGS=dev                # consul service tag
            - CONSUL_SERVICEPORT=9000               # consul service port
            - CONSUL_CHECKTYPE=tcp                  # consul health check type
            - PHP_MANAGER=static                    # process manager mode (static/dynamic/ondemand)
            #- PHP_MAXCHILDREN=5                    # maximum children (static/ondemand)
            #- PHP_STARTSERVERS=2                   # number of startup processes (dynamic)
            #- PHP_MINSPARESERVERS=1                # minimum idle processes (dynamic)
            #- PHP_MAXSPARESERVERS=3                # maximum idle processes (dynamic)
            #- PHP_PROCESSIDLETIMEOUT=10s           # number of seconds before killing idle processes
            #- PHP_MAXREQUESTS=500                  # number of requests before respawning
            - PHP_STATUSPATH=/status                # path of status page
            - PHP_PINGPATH=/ping                    # path of ping page
            #- PHP_PINGRESPONSE=pong                # response of ping
            #- PHP_ACCESSLOG=0                      # enable access log
            #- PHP_ACCESSFORMAT=                    # access log format
            #- PHP_SLOWLOG=0                        # enable slow log
            #- PHP_REQUESTSLOWLOGTIMEOUT=0          # timeout for logging slow requests
            #- PHP_REQUESTTERMINATETIMEOUT=0        # timeout for killing running processes
            #- PHP_CLEARENV=yes                     # clear environment of processes
            #- PHPINI_USERINI_CACHETTL=300          # PHP user-defined php.ini TTL cache
            #- PHPINI_USERINI_FILENAME=.user.ini    # PHP user-defined php.ini filename
            #- PHPINI_MAXEXECUTIONTIME=30           # PHP maximum execution time
            #- PHPINI_MAXINPUTTIME=60               # PHP maximum input time
            #- PHPINI_MEMORYLIMIT=128M              # PHP memory limit
            #- PHPINI_POSTMAXSIZE=8M                # PHP post max size
            #- PHPINI_UPLOADMAXFILESIZE=2M          # PHP upload max file size
            #- PHPINI_ALWAYSPOPULATERAWPOSTDATA=0   # PHP always populate raw post data
            #- PHPINI_DATE_TIMEZONE=                # PHP date timezone
