#!/usr/bin/with-contenv sh

cd /usr/local/chronograf || exit 1
exec s6-setuidgid chronograf /usr/local/chronograf/usr/bin/chronograf -r -b /var/lib/chronograf/chronograf-v1.db \
    ${CHRONOGRAF_OPTIONS}
