#!/usr/bin/with-contenv sh

if [ ! -z "${VAULT_TEMPLATE}" ]; then
    echo "==> Enabling template ${VAULT_TEMPLATE}"

    cp "/etc/consul-template/templates/vault/${VAULT_TEMPLATE}"/*.hcl /etc/consul-template/conf.d/
fi
