#!/usr/bin/with-contenv sh

if [ ! -z ${VAULT_TEMPLATE} ]; then
    echo "==> Enabling vault template '${VAULT_TEMPLATE}'"

    cp "/etc/consul-template/templates/vault/${VAULT_TEMPLATE}.conf" /etc/consul-template/conf-services.d/10-vault.conf
fi
