version: '3.8'

volumes:
    redis:

services:
    redis:
        image: bhuisgen/alpine-redis
        ports:
            - "6379:6379"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - redis:/var/lib/redis                  # volume for data
        environment:
            - ENV=local                             # environment name
            #- REDIS_TEMPLATE=generic               # configuration template

            #
            # template generic
            #
