version: '3.7'

services:
    perl:
        image: bhuisgen/alpine-perl
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - ENV=local                             # environment name
