#!/usr/bin/with-contenv sh

if [ ! -z "${POSTFIX_TEMPLATE}" ]; then
    echo "==> Enabling template ${POSTFIX_TEMPLATE}"

    cp "/etc/consul-template/templates/postfix/${POSTFIX_TEMPLATE}"/*.hcl /etc/consul-template/conf.d/
fi
