#!/usr/bin/with-contenv sh

if [ ! -z ${POSTFIX_TEMPLATE} ]; then
    echo "==> Enabling service template '${POSTFIX_TEMPLATE}'"

    cp "/etc/consul-template/templates/postfix/${POSTFIX_TEMPLATE}/postfix.conf" /etc/consul-template/conf-services.d/10-postfix.conf
fi
