version: '3.7'

services:
    rng:
        image: bhuisgen/alpine-rng
        privileged: true
        network_mode: none
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - ENV=local                             # environment name
            - RNG_OPTIONS=--no-tpm=1                # rng options
