version: '3.8'

services:
    rng:
        image: bhuisgen/alpine-rng
        privileged: true
        network_mode: none
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - ENV=local                             # environment name
