#!/usr/bin/with-contenv sh

if [ ! -z "${DNSMASQ_TEMPLATE}" ]; then
    echo "==> Enabling template ${DNSMASQ_TEMPLATE}"

    cp "/etc/consul-template/templates/dnsmasq/${DNSMASQ_TEMPLATE}"/*.hcl /etc/consul-template/conf.d/
fi
