version: '3.7'

volumes:
    mongodb:

services:
    mongodb:
        image: bhuisgen/alpine-mongodb
        ports:
            - "27017:27017"
            - "28017:28017"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - mongodb:/var/lib/mongodb              # volume for data
        environment:
            - ENV=local                             # environment name
            #- MONGODB_TEMPLATE=generic             # configuration template

            #
            # template generic
            #
