version: '3.7'

volumes:
    archiva:

services:
    archiva:
        image: bhuisgen/alpine-archiva
        ports:
            - "8080:8080"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - archiva:/var/lib/archiva              # volume for data
        environment:
            - ENV=local                             # environment name
            #- ARCHIVA_TEMPLATE=generic             # configuration template

            #
            # template generic
            #
