version: '3.5'

volumes:
    archiva:

services:
    archiva:
        depends_on:
            - consul                                        # consul agent
        image: bhuisgen/alpine-archiva
        ports:
            - "8080:8080"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - archiva:/var/lib/archiva                      # volume for data
        environment:
            - ENV=local                                     # environment name
            - CONSUL_AGENT=consul                           # consul agent hostname/IP
            #- CONSUL_PORT=8500                             # consul agent port
            #- CONSUL_KEYPREFIX=path/prefix/                # consul key prefix path
            - CONSUL_SERVICENAME=archiva                    # consul service name
            - CONSUL_SERVICETAGS=local                      # consul service tag
            - CONSUL_SERVICEPORT=8080                       # consul service port
            - CONSUL_CHECKTYPE=tcp                          # consul health check type
