version: '3.7'

volumes:
    git:

services:
    git:
        image: bhuisgen/alpine-git
        ports:
            - "2222:22"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - git:/home/git                         # volume for data
        environment:
            - ENV=local                             # environment name
            #- GIT_TEMPLATE=generic                 # configuration template

            #
            # template generic
            #
