version: '3.7'

volumes:
    backuppc:

services:
    backuppc:
        image: bhuisgen/alpine-backuppc
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /srv/backuppc:/var/lib/backuppc       # volume for storage
            - backuppc:/var/www                     # volume for web files
        environment:
            - ENV=local                             # environment name
