version: '3.8'

volumes:
    backuppc:

services:
    backuppc:
        image: bhuisgen/alpine-backuppc
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /srv/backuppc:/var/lib/backuppc       # volume for storage
            - backuppc:/var/www                     # volume for web files
        environment:
            - ENV=local                             # environment name
            #- BACKUPPC_TEMPLATE=generic            # configuration template

            #
            # template generic
            #
            #- BACKUPPC_INIT=1                      # enable default config initialization
            #- BACKUPPC_MAILHOST=                   # mail host
            #- BACKUPPC_MAILPORT=                   # mail port
            #- BACKUPPC_MAILFROM=                   # mail from address
            #- BACKUPPC_MAILUSER=                   # mail auth user
            #- BACKUPPC_MAILUSERPASSWORD=           # mail auth password
