version: '3.5'

volumes:
    backuppc:

services:
    consul:
        image: bhuisgen/alpine-consul
        ports:
            - "8500:8500"
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - CONSUL_OPTIONS=-server -bootstrap-expect 1 -client 0.0.0.0 -ui    # minimal server options

    backuppc:
        depends_on:
            - consul
        image: bhuisgen/alpine-backuppc
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - backuppc:/var/www                             # volume for web files
            - /srv/backuppc:/var/lib/backuppc               # volume for storage
        environment:
            - CONSUL_AGENT=consul                           # consul agent hostname/IP
            #- CONSUL_PORT=8500                             # consul agent port
            #- CONSUL_KEYPREFIX=path/prefix/                # consul key prefix path
            - CONSUL_SERVICENAME=backuppc                   # consul service name
            - CONSUL_SERVICETAGS=dev                        # consul service tag
            - CONSUL_SERVICEPORT=9000                       # consul service port
            - CONSUL_CHECKTYPE=tcp                          # consul health check type
