version: '3.5'

volumes:
    backuppc:
    backuppc-www:

services:
    backuppc:
        depends_on:
            - consul                                # consul agent
        image: bhuisgen/alpine-backuppc
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /srv/backuppc:/var/lib/backuppc       # volume for storage
            - backuppc:/var/www                     # volume for web files
        environment:
            - ENV=local                             # environment name
            - CONSUL_AGENT=consul                   # consul agent hostname/IP
            #- CONSUL_PORT=8500                     # consul agent port
            #- CONSUL_KEYPREFIX=path/prefix/        # consul key prefix path
            - CONSUL_SERVICENAME=backuppc           # consul service name
            - CONSUL_SERVICETAGS=local              # consul service tag
            - CONSUL_SERVICEPORT=9000               # consul service port
            - CONSUL_CHECKTYPE=tcp                  # consul health check type
