version: '3.8'

volumes:
    elasticsearch:

services:
    elasticsearch:
        image: bhuisgen/alpine-elasticsearch
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - elasticsearch:/var/lib/elasticsearch      # volume for data
        environment:
            - ENV=local                                 # environment name
            #- ELASTICSEARCH_TEMPLATE=generic           # configuration template

            #
            # template generic
            #

            #- ELASTICSEARCH_CLUSTERNAME=               # cluster name
            #- ELASTICSEARCH_NODENAME=                  # node name
            #- ELASTICSEARCH_NODEATTRRACK=              # node custom attributes
            #- ELASTICSEARCH_JVMHEAPSIZE=1g             # JVM heap size
