version: '3.8'

services:
    mailhog:
        image: bhuisgen/alpine-mailhog
        ports:
            - "1025:1025"
            - "8025:8025"
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - ENV=local                             # environment name
