version: '3.5'

services:
    foo:
        depends_on:
            - consul                                    # consul agent
        ports:
            - "1234:1234"
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - ENV=local                                 # environment name
            #- CONTAINER_RESOLVER=route                 # IP resolver method for container (route/interface, default: route)
            #- CONTAINER_RESOLVER_INTERFACENAME=eth0    # network interface name for IP resolver (default: eth0)
            #- CONTAINER_RESOLVER_INTERFACETYPE=inet    # network interface type for IP resolver (inet/inet6, default: inet)
            - CONSUL_AGENT=consul                       # agent hostname
            #- CONSUL_PORT=8500                         # agent port
            #- CONSUL_TLS=0                             # enable TLS
            #- CONSUL_TLSCAFILE=                        # TLS CA certificate file
            #- CONSUL_TLSCERTFILE=                      # TLS client certificate file (client)
            #- CONSUL_TLSKEYFILE=                       # TLS client certificate key file (client)
            #- CONSUL_TLSSERVERNAME=                    # SNI server name for validation
            #- CONSUL_TLSVERIFY=0                       # enable TLS peer verification
            #- CONSUL_TOKEN=                            # API token
            #- CONSUL_KEYPREFIX=                        # keystore prefix path
            - CONSUL_SERVICENAME=foo                    # service name to register
            - CONSUL_SERVICETAGS=local                  # service tags (optional)
            - CONSUL_SERVICEPORT=1234                   # service port
            - CONSUL_CHECKTYPE=tcp                      # health check type (none/http/script/tcp/ttl, default: none)
            - CONSUL_CHECKINTERVAL=15s                  # health check interval
            #- CONSUL_DEREGISTERCRITICALSERVICEAFTER=   # delay after which the service will be deregistered if this check remains critical (0 to disable)
            #- CONSUL_RESOLVER=container                # IP resolver method for consul service (container/route/interface, by default container)
            #- CONSUL_RESOLVER_INTERFACENAME=eth0       # network interface name for IP resolver (default: eth0)
            #- CONSUL_RESOLVER_INTERFACETYPE=inet       # network interface type for IP resolver (inet/inet6, default: inet)
            #- CONSUL_WAITFOR_SERVICENAME=              # consul service name to wait for starting
            #- CONSUL_WAITFOR_SERVICETAG=               # consul service tag to wait for starting
            #
            # HTTP health check
            #
            #- CONSUL_CHECKTYPE=http
            #- CONSUL_CHECKHTTPURL=http://foo:1234      # HTTP custom URL
            #- CONSUL_CHECKHTTPPATH=/                   # HTTP path for auto-generated URL (http://<container_ip>:<service_port><path>)
            #- CONSUL_CHECKHTTPTLSSKIPVERIFY=0          # skip TLS certificate verification
            #- CONSUL_CHECKINTERVAL=15s                 # check interval
            #- CONSUL_DEREGISTERCRITICALSERVICEAFTER=   # delay after which the service will be deregistered if this check remains critical (0 to disable)
            #
            # Script health check
            #
            #- CONSUL_CHECKTYPE=script
            #- CONSUL_CHECKSCRIPT=/usr/local/bin/healthcheck.sh # script to execute
            #- CONSUL_CHECKDOCKERCONTAINERID=                   # docker container id
            #- CONSUL_CHECKSHELL=/bin/bash                      # custom shell
            #- CONSUL_CHECKINTERVAL=15s                         # check interval
            #- CONSUL_DEREGISTERCRITICALSERVICEAFTER=           # delay after which the service will be deregistered if this check remains critical (0 to disable)
            #
            # TCP health check
            #
            #- CONSUL_CHECKTYPE=tcp
            #- CONSUL_CHECKADDR=static                  # custom TCP address if different from service registration
            #- CONSUL_CHECKPORT=5678                    # custom TCP port if different from service registration
            #- CONSUL_CHECKINTERVAL=15s                 # check interval
            #- CONSUL_DEREGISTERCRITICALSERVICEAFTER=   # delay after which the service will be deregistered if this check remains critical (0 to disable)

            #
            # TTL health check
            #
            #- CONSUL_CHECKTYPE=ttl
            #- CONSUL_CHECKTTL=15s                      # TTL update
            #- CONSUL_DEREGISTERCRITICALSERVICEAFTER=   # delay after which the service will be deregistered if this check remains critical (0 to disable)
